CREATE TABLE accounts (
 id UUID PRIMARY KEY, username VARCHAR(24) NOT NULL UNIQUE,
 password_hash TEXT NOT NULL, approved BOOLEAN NOT NULL DEFAULT FALSE,
 admin BOOLEAN NOT NULL DEFAULT FALSE, entered BOOLEAN NOT NULL DEFAULT FALSE, q INTEGER NOT NULL DEFAULT 0,
 r INTEGER NOT NULL DEFAULT 0, color VARCHAR(7) NOT NULL,
 created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);
CREATE UNIQUE INDEX accounts_username_lower ON accounts(lower(username));
CREATE TABLE sessions (
 token_hash VARCHAR(64) PRIMARY KEY, account_id UUID NOT NULL REFERENCES accounts(id) ON DELETE CASCADE,
 expires_at TIMESTAMPTZ NOT NULL
);
CREATE INDEX sessions_account ON sessions(account_id);
CREATE TABLE worlds (id INTEGER PRIMARY KEY CHECK(id=1), document TEXT NOT NULL);
CREATE TABLE admin_audit (
 id BIGSERIAL PRIMARY KEY, actor UUID REFERENCES accounts(id), action TEXT NOT NULL,
 target TEXT NOT NULL, created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);
