import {useRef,useState} from 'react';
import {Footprints,Swords,SkipForward,LogOut,LocateFixed,Plus,Minus,Maximize} from 'lucide-react';
import {api} from './api';
import type {BattleState,Hex} from './types';
const SIZE=36;
const xy=(h:Hex)=>({x:1.5*SIZE*h.q,y:Math.sqrt(3)*SIZE*(h.r+h.q/2)});
const distance=(a:Hex,b:Hex)=>Math.max(Math.abs(a.q-b.q),Math.abs(a.r-b.r),Math.abs(a.q+a.r-b.q-b.r));
const sides=(h:Hex,r:number)=>[h.q,h.q+h.r,h.r,-h.q,-h.q-h.r,-h.r].flatMap((n,i)=>n===r?[i]:[]);
function polygon(h:Hex,r=SIZE-1){const p=xy(h);return Array.from({length:6},(_,i)=>{const a=i*Math.PI/3;return `${p.x+r*Math.cos(a)},${p.y+r*Math.sin(a)}`;}).join(' ');}
function tiles(radius:number){const result:Hex[]=[];for(let r=-radius;r<=radius;r++)for(let q=-radius;q<=radius;q++)if(distance({q:0,r:0},{q,r})<=radius)result.push({q,r});return result;}
function Sprite({color='#b87855'}:{color?:string}){return <g shapeRendering="crispEdges"><ellipse cy="13" rx="15" ry="5" fill="#253b38" opacity=".23"/><path d="M-10-9h20v22H-10z" fill="#34483f"/><path d="M-9-8h18v17H-9z" fill={color}/><path d="M-6-7h4V6h-4z" fill="#ffffff" opacity=".25"/><path d="M-9 8h7v8h-7zm12 0h7v8H3z" fill="#394039"/><path d="M-8-25H8v18H-8z" fill="#efd4a4"/><path d="M-9-27H8v5H-9zM-11-23h6v9h-6zM5-23h5v5H5z" fill="#67513d"/><path d="M-3-18h2v3h-2zm7 0h2v3H4z" fill="#3b4037"/><path d="M-13-6h5v11h-5z" fill="#efd4a4"/><path d="M12-14h3v21h-3z" fill="#e9e8cb"/><path d="M9 4h9v3H9z" fill="#a58a51"/><path d="M-8 3H8v3H-8z" fill="#795c3d"/></g>;}
function Tree(){return <g shapeRendering="crispEdges"><ellipse cy="15" rx="23" ry="7" fill="#486448" opacity=".22"/><path d="M-4-6H4v24H-4z" fill="#76634a"/><path d="M-2-3H2v20H-2z" fill="#ab8857"/><path d="M-20-31h40v25h-40zM-14-43h28v44h-28zM-25-23h50v13h-50z" fill="#486c53"/><path d="M-20-30h33v20h-33zM-12-42h25v28h-25zM-25-21h35v10h-35z" fill="#6d935e"/><path d="M-12-41H5v8h-17zM-20-28h12v10h-12zM6-30h9v6H6z" fill="#98b777"/><path d="M-7-23H5v9H-7zM10-14h7v5h-7z" fill="#7da464"/><path d="M-15-9h8v4h-8z" fill="#afbf7c"/></g>;}
function Rock(){return <g shapeRendering="crispEdges"><ellipse cy="10" rx="19" ry="5" fill="#516149" opacity=".2"/><path d="M-17-4h8v-9H7v5h9v19h-33z" fill="#788778"/><path d="M-15-3h8v-8H5v5h8v9h-28z" fill="#b0b6a0"/><path d="M-6-10H4v7H-6z" fill="#d0d0b6"/><path d="M-14 5H3v5h-17z" fill="#95a18a"/><path d="M8 5h10v8H8z" fill="#6e865d"/></g>;}
export function BattleView({battle,me,connected,clock,onChanged,onMessage}:{battle:Extract<BattleState,{active:true}>;me:string;connected:boolean;clock:number;onChanged:()=>Promise<void>;onMessage:(message:string)=>void}){
 const [selected,setSelected]=useState<Hex|null>(null),[busy,setBusy]=useState(false),[zoom,setZoom]=useState(1),[center,setCenter]=useState({x:0,y:0});
 const drag=useRef<{x:number;y:number;cx:number;cy:number;moved:boolean}|null>(null);
 const own=battle.actors.find(a=>a.accountId===me),current=battle.actors.find(a=>a.accountId===battle.turnAccountId);
 const target=selected?battle.actors.find(a=>a.q===selected.q&&a.r===selected.r):undefined;
 const myTurn=battle.turnAccountId===me&&!!own&&own.entryRound<=battle.round;
 const adjacent=!!own&&!!selected&&distance(own,selected)===1;
 const enabled=connected&&myTurn&&!busy;
 const ownEdges=own?sides(own,battle.radius):[];
 const recentAttack=[...battle.events].reverse().find(e=>e.kind==='attack'&&clock-e.happenedAt<1250);
 const notice=[...battle.events].reverse().find(e=>clock-e.happenedAt<5000&&['withdraw-interrupted','withdraw-blocked','attack'].includes(e.kind));
 const noticeText=notice?(notice.kind==='withdraw-interrupted'?`${battle.actors.find(a=>a.accountId===notice.actorId)?.username||'旅人'} 的撤离被攻击打断`:notice.kind==='withdraw-blocked'?'目的地暂时无法进入，撤离已取消':'攻击已执行'):'';
 const seconds=Math.max(0,Math.ceil((battle.turnDeadline-clock)/1000));
 const span=890/zoom;
 async function command(path:string,body:object){if(busy)return;setBusy(true);try{await api('/battle/'+path,{battleId:battle.id,...body});await onChanged();}catch(e){onMessage((e as Error).message);}finally{setBusy(false);}}
 function locate(h:Hex){setSelected(h);setCenter(xy(h));setZoom(1.5);}
 return <section className="battle-surface" aria-label="局部战场">
 <div className="battle-grain" aria-hidden="true"/>
 <div className="initiative-shell"><div className="initiative-caption"><span>第 {battle.round} 轮</span><b>{myTurn?'轮到你行动':`${current?.username||'旅人'} 的回合`}</b><span>{seconds} 秒 · {battle.turnPoints}/6 行动点</span></div>
 <div className="initiative-strip" aria-label="本轮行动顺序">{battle.actors.map((a,i)=>{const waiting=a.entryRound>battle.round,active=a.accountId===battle.turnAccountId,acted=!waiting&&a.initiative<(current?.initiative??0);return <button key={a.accountId} className={'initiative-portrait '+(active?'current ':'')+(acted?'acted ':'')+(!a.online?'offline ':'')+(waiting?'reinforcement':'')} onClick={()=>locate(a)} title={`定位 ${a.username}`} aria-label={`定位 ${a.username}${active?'，当前回合':''}`}><span className="portrait-order">{i+1}</span><svg viewBox="-25 -33 50 54"><Sprite color={a.color}/></svg><strong>{a.username}{a.accountId===me?' · 你':''}</strong><small>{a.withdrawDirection!=null?'正在撤离':waiting?'下轮加入':!a.online?'离线':active?'行动中':acted?'已行动':'待行动'}</small></button>;})}</div></div>
 <svg className="battle-board" viewBox={`${center.x-span/2} ${center.y-span/2} ${span} ${span}`} aria-label="六边形战场，外圈是撤离区域" onWheel={e=>setZoom(z=>Math.max(.65,Math.min(2.8,z*(e.deltaY>0?.9:1.1))))} onPointerDown={e=>{drag.current={x:e.clientX,y:e.clientY,cx:center.x,cy:center.y,moved:false};}} onPointerMove={e=>{const d=drag.current;if(!d)return;const dx=e.clientX-d.x,dy=e.clientY-d.y;if(Math.abs(dx)+Math.abs(dy)>5){d.moved=true;const scale=span/Math.min(e.currentTarget.clientWidth,e.currentTarget.clientHeight);setCenter({x:d.cx-dx*scale,y:d.cy-dy*scale});}}} onPointerUp={()=>{setTimeout(()=>{drag.current=null;},0);}} onPointerLeave={()=>{drag.current=null;}}>
 {tiles(battle.radius).map(h=>{const p=xy(h),edge=sides(h,battle.radius),outer=edge.length>0,blocked=outer&&edge.every(d=>!battle.edges[d].walkable),chosen=selected?.q===h.q&&selected.r===h.r,marked=battle.intents.some(i=>i.q===h.q&&i.r===h.r),near=!!own&&distance(own,h)===1,n=((Math.imul(h.q+713+battle.worldQ,374761393)^Math.imul(h.r+997+battle.worldR,668265263))>>>0),occupied=battle.actors.some(a=>a.q===h.q&&a.r===h.r);return <g key={`${h.q},${h.r}`} className={'battle-cell '+(outer?'outer ':'')+(blocked?'blocked ':'')+(near&&myTurn?'reachable ':'')+(chosen?'selected ':'')+(marked?'marked':'')}>
 <polygon className="cell-ground" points={polygon(h)} fill={['#b9cc8b','#b5c986','#c0d090','#bacb88'][n%4]} onClick={()=>{if(!drag.current?.moved)setSelected(h);}} tabIndex={0} role="button" aria-label={`战场格 ${h.q}, ${h.r}${outer?'，撤离区':''}`} onKeyDown={e=>{if(e.key==='Enter'||e.key===' '){e.preventDefault();setSelected(h);}}}/>
 <g pointerEvents="none" opacity={outer?.42:1} transform={`translate(${p.x} ${p.y})`}><path d="M-19 12h3v-5m0 5h4v-3M12-18h3v-4m0 4h4v-2" stroke="#72965e" strokeWidth="2" fill="none"/><path d="M-10-15h5v2h-5M15 15h4v2h-4" fill="#e0dda0"/>{!outer&&n%9===0?<g opacity={occupied?.35:1} transform="translate(10 -2) scale(.9)"><Tree/></g>:!outer&&n%7===0?<g transform="translate(12 5) scale(.85)"><Rock/></g>:null}{outer&&<text className="edge-cell-label" y="5">{edge.map(d=>battle.edges[d].walkable?['→','↘','↙','←','↖','↗'][d]:'×').join(' ')}</text>}</g>
 {marked&&<polygon className="battle-intent-ring" points={polygon(h,SIZE-4)} pointerEvents="none"/>}</g>;})}
 {battle.edges.map(e=>{const a=e.direction*Math.PI/3,p={x:Math.cos(a)*405,y:Math.sin(a)*405};return <g key={e.direction} transform={`translate(${p.x} ${p.y})`} className={'battle-side-label '+(!e.walkable?'blocked':'')} pointerEvents="none"><rect x="-49" y="-16" width="98" height="40" rx="7"/><text textAnchor="middle" y="0">{e.name} · {e.walkable?e.battleId?'另一战场':'可撤离':'不可通行'}</text><text textAnchor="middle" y="15" className="destination">{e.destination}</text></g>;})}
 {[...battle.actors].sort((a,b)=>xy(a).y-xy(b).y).map(a=>{const p=xy(a),active=a.accountId===battle.turnAccountId;return <g key={a.accountId} transform={`translate(${p.x} ${p.y})`} className={'battle-actor '+(!a.online?'offline':'')} onClick={()=>{if(!drag.current?.moved)setSelected(a);}} style={{cursor:'pointer'}}><ellipse cy="12" rx="21" ry="9" fill="none" stroke={active?'#fff1aa':a.accountId===me?'#71c4d0':'#72836a'} strokeWidth={active?3:2}/><Sprite color={a.color}/><text className="battle-actor-name" y="-35">{a.username}{a.accountId===me?' · 你':''}</text>{a.withdrawDirection!=null&&<text className="battle-wait-label" y="29">正在撤离…</text>}{!a.online&&<text className="battle-wait-label" y="40">离线</text>}</g>;})}
 {recentAttack&&<g key={recentAttack.id} transform={`translate(${xy({q:recentAttack.q!,r:recentAttack.r!}).x} ${xy({q:recentAttack.q!,r:recentAttack.r!}).y})`} pointerEvents="none"><path className="battle-attack-flash" d="M-22 20L22-25M-16-22L18 19" stroke="#fff1c0" strokeWidth="7"/></g>}
 </svg>
 <div className="battle-tools"><button title="放大战场" aria-label="放大战场" onClick={()=>setZoom(z=>Math.min(2.8,z*1.2))}><Plus size={18}/></button><button title="缩小战场" aria-label="缩小战场" onClick={()=>setZoom(z=>Math.max(.65,z/1.2))}><Minus size={18}/></button><button title="查看全场" aria-label="查看全场" onClick={()=>{setCenter({x:0,y:0});setZoom(.8);}}><Maximize size={18}/></button><button title="定位自己" aria-label="定位自己" onClick={()=>own&&locate(own)}><LocateFixed size={18}/></button></div>
 <div className="battle-actions"><div className="battle-selection">{own?.withdrawDirection!=null?'已准备撤离 · 下次轮到你时离开，受到实际攻击会打断':own&&own.entryRound>battle.round?'已进入战场 · 下一轮开始行动':selected?`${target?.username||'草地'} · ${selected.q}, ${selected.r}`:'选择格子移动，或选择相邻角色标记攻击'}</div><div className="battle-action-buttons"><button className="soft-button" disabled={!enabled||!adjacent||!!target||battle.turnPoints<1} onClick={()=>selected&&void command('step',selected)}><Footprints size={15}/>移动 · 1 点</button><button className="soft-button battle-attack-button" disabled={!enabled||!adjacent||!target||target.accountId===me||battle.attackUsed||battle.turnPoints<2} onClick={()=>target&&void command('attack',{targetId:target.accountId})}><Swords size={15}/>标记攻击 · 2 点</button><button className="soft-button" disabled={!enabled} onClick={()=>void command('end-turn',{})}><SkipForward size={15}/>结束回合</button></div>
 {ownEdges.length>0&&<div className="withdraw-options">{ownEdges.map(d=>{const e=battle.edges[d];return <div className="withdraw-row" key={d}><span><b>{e.name} → {e.destination}</b><small>{!e.walkable?'此方向不可通行':e.battleId?'注意：将进入另一场战斗':'返回相邻大世界格'}</small></span><button disabled={!enabled||!e.walkable} onClick={()=>void command('withdraw',{direction:d,force:false})}><LogOut size={13}/>准备撤离</button><button disabled={!enabled||!e.walkable||!battle.turnStartEdge||battle.turnPoints!==6} onClick={()=>void command('withdraw',{direction:d,force:true})} title="回合开始已在外圈，花费完整6点立即离开">强退 · 6 点</button></div>;})}</div>}
 <div className="battle-feedback" role="status" aria-live="polite">{noticeText}</div><div className="battle-quiet">{ownEdges.length?'普通撤离会立即结束本回合；强制撤离需回合开始已在外圈。':'半透明外圈可申请撤离 · 红格攻击在攻击者下回合执行'}</div></div>
 </section>;
}
