import {useEffect,useRef,useState} from 'react';
import {Skull,Axe,TreePine,Mountain,Swords,Shield,Shirt,Footprints,Hand,Gem,Crown,X} from 'lucide-react';
import type {Character,Item,LootContainer} from './types';
import './character.css';
export function ItemIcon({code}:{code:string}){return code==='wood'?<TreePine/>:code==='stone'?<Mountain/>:code==='axe'?<Axe/>:code==='buckler'||code==='tower_shield'?<Shield/>:code==='bandage'?<Hand/>:code==='spear'?<svg width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="1.8"><path d="M4 21L17 7M14 7L21 2 20 10Z"/></svg>:<svg width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="1.8"><path d="M3 22l7-9m0 0l3-3m0 0l2-2M15 3l1 2m5-1l-1 2m3 5l-3-1"/><circle cx="17" cy="8" r="4"/></svg>;}
const attributes=[['strength','力量'],['agility','敏捷'],['constitution','体魄'],['intellect','智识'],['perception','感知'],['willpower','意志']] as const;
export function CharacterPanel({corpses,onLoot,onDrop,character,items,locked,onEquip}:{corpses:LootContainer[];onLoot:(id:string)=>void;onDrop:()=>void;character:Character|null;items:Item[];locked:boolean;onEquip:(main:string|null,off?:string|null)=>Promise<void>}){
 const [selected,setSelected]=useState<string|null>(null),[busy,setBusy]=useState(false);
 const detailRef=useRef<HTMLElement|null>(null);
 useEffect(()=>{if(selected)detailRef.current?.scrollIntoView({block:'nearest'});},[selected]);
 const detail=items.find(i=>i.code===selected),equipped=items.find(i=>i.code===character?.weapon),offhand=items.find(i=>i.code===character?.offhand);
 async function equip(main:string|null,off=character?.offhand??null){setBusy(true);try{await onEquip(main,off);}finally{setBusy(false);}}
 if(!character)return <p>正在读取人物…</p>;
 return <div className="character-panel"><section className="paper-doll"><header><strong>{character.name}</strong><span>{character.life==='soul'?'灵魂':character.life==='down'?'倒地 · 等待救援':'冒险者'}</span></header>
 <div className="gear-column">{[[Crown,'头部'],[Shirt,'护甲'],[Hand,'手套']].map(([Icon,label])=>{const Glyph=Icon as typeof Crown;return <button key={String(label)} className="gear-slot locked" disabled title={`${label} · 尚未开放`}><Glyph/><small>{String(label)}</small></button>;})}<button className="gear-slot equipped" aria-label="武器槽" onClick={()=>setSelected(character.weapon)} title={equipped?.description||'空手：相邻单格，2伤害，2行动点'}>{equipped?<ItemIcon code={equipped.code}/>:<Swords/>}<small>{equipped?.name||'空手'}</small></button></div>
 <div className={'character-portrait '+character.life}><svg viewBox="0 0 120 200" role="img" aria-label="全身像素角色" shapeRendering="crispEdges"><ellipse cx="60" cy="182" rx="32" ry="8" fill="#263b37" opacity=".3"/><path d="M40 42h40v39H40" fill="#ecd0a2"/><path d="M35 36h48v12H35M33 44h12v22H33M74 43h12v12H74" fill="#594637"/><path d="M49 58h4v6h-4M69 58h4v6h-4" fill="#35443b"/><path d="M35 82h50v62H35" fill="#426e5d"/><path d="M40 86h15v49H40" fill="#6e9e7a"/><path d="M26 88h10v49H26M85 88h10v49H85" fill="#d4b386"/><path d="M36 136h48v10H36" fill="#8f6b43"/><path d="M57 134h9v13h-9" fill="#e4c37c"/><path d="M39 146h17v32H39M65 146h17v32H65" fill="#435049"/><path d="M33 173h24v11H33M64 173h26v11H64" fill="#453e32"/>{equipped&&<g stroke="#d8dcbf" strokeWidth="4"><path d="M101 160V90"/>{equipped.code==='spear'?<path d="M101 69l-6 22h12Z" fill="#d8dcbf"/>:equipped.code==='axe'?<path d="M101 88h12v18h-12" fill="#abbab1"/>:<><path d="M101 90l8-15"/><circle cx="109" cy="68" r="8" fill="#91a39c"/></>}</g>}</svg><span>{equipped?.name||'未装备武器'}</span></div>
 <div className="gear-column"><button className={offhand?'gear-slot equipped':'gear-slot'} aria-label="副手槽" onClick={()=>setSelected(character.offhand)} title={offhand?.description||'副手可装备单手盾；双手盾会占用双手'}>{offhand?<ItemIcon code={offhand.code}/>:<Shield/>}<small>{offhand?.name||'副手'}</small></button>{[[Gem,'项链'],[Gem,'饰品'],[Footprints,'鞋子']].map(([Icon,label])=>{const Glyph=Icon as typeof Shield;return <button key={String(label)} className="gear-slot locked" disabled title={`${label} · 尚未开放`}><Glyph/><small>{String(label)}</small></button>;})}</div>
 </section><section className="character-vitals"><div className="vitals-line">生命 {character.hp}/{character.maxHp}<meter min={0} max={character.maxHp} value={character.hp}/></div><div className="vitals-line">倒地 {character.downHp}/{character.maxDownHp}<meter min={0} max={character.maxDownHp} value={character.downHp}/></div>{character.life==='down'&&<small>无法行动，等待其他旅人救起。</small>}</section>
 <div className="attribute-grid">{attributes.map(([key,name])=><div key={key} title={`${name}基础值。${key==='agility'?'影响开战先攻判定。':'后续开放成长与派生效果。'}`}><span>{name}</span><strong>{character[key]}</strong></div>)}</div>
 <div className="equipment-row"><p>{equipped?`${equipped.name} · ${equipped.damage} 伤害 · ${equipped.attack_cost} 行动点`:'空手 · 2 伤害 · 2 行动点'}{offhand?`；${offhand.name} · 护甲+${offhand.passive_armor}`:''}</p>{(equipped||offhand)&&<button disabled={locked||busy} onClick={()=>void onEquip(null,null)}>全部收起</button>}</div>
 <button className="pixel-btn" disabled={character.life!=='alive'} onClick={onDrop}>丢弃物品</button>
 <h3>背包</h3><div className="inventory-grid">{items.filter(i=>i.quantity>0).map(i=><button key={i.code} className={'item-slot '+(selected===i.code?'selected':'')} aria-label={`${i.name}，数量${i.quantity}`} onClick={()=>setSelected(i.code)} title={`${i.name}：${i.description}${i.kind==='weapon'?` · ${i.damage}伤害 / ${i.attack_cost}行动点`:''}`}><ItemIcon code={i.code}/><span>{i.name}</span><b>{i.quantity}</b></button>)}</div>
 <div className="inventory-grid">{corpses.map(c=><button key={c.id} className="item-slot corpse-slot" disabled={character.life!=='alive'} onClick={()=>onLoot(c.id)} title="独立占格，不可堆叠；携带期间暂停消失计时"><Skull/><span>{c.name}</span></button>)}</div>
 {!corpses.length&&!items.some(i=>i.quantity>0)&&<p className="empty">背包还是空的，去收集些材料吧。</p>}
 {detail&&<section ref={detailRef} className="item-detail" aria-live="polite"><button aria-label="关闭物品详情" className="icon-button" onClick={()=>{setSelected(null);}}><X size={14}/></button><strong>{detail.name}</strong><p>{detail.description}</p>{detail.kind==='weapon'&&<><p>伤害 {detail.damage} · 消耗 {detail.attack_cost} 点</p><button disabled={locked||busy||detail.quantity<1||character.weapon===detail.code} onClick={()=>void equip(detail.code,detail.hand_usage==='main_two'?null:character.offhand)}>{character.weapon===detail.code?'已装备':locked?'战斗或特殊状态中不能换装':'装备主手'}</button></>}{detail.kind==='shield'&&<><p>护甲 +{detail.passive_armor} · 举盾减伤 {detail.guard_reduction}</p><button disabled={locked||busy||detail.quantity<1||character.offhand===detail.code} onClick={()=>void equip(detail.hand_usage==='off_two'?null:character.weapon,detail.code)}>{character.offhand===detail.code?'已装备':locked?'战斗或特殊状态中不能换装':'装备盾牌'}</button></>}</section>}
 </div>;
}
export function LifePanel({character,clock,busy,onAction,onLocate}:{character:Character;clock:number;busy:boolean;onAction:(action:string)=>void;onLocate:()=>void}){
 const [dismissed,setDismissed]=useState(false),[confirm,setConfirm]=useState(false);
 useEffect(()=>{setDismissed(false);setConfirm(false);},[character.life]);
 if(character.life==='down')return <>{!dismissed?<div className="death-overlay"><section role="dialog" aria-modal="true" aria-labelledby="down-title"><h2 id="down-title">你已倒地</h2><p>{confirm?'确认结束生命？你将以灵魂回到绑定城市。':'可以等待旅人救援，或选择结束生命，以灵魂回归。'}</p><button onClick={()=>{setDismissed(true);setConfirm(false);}}>等待救援</button><button disabled={busy} onClick={()=>{if(confirm)onAction('surrender');else setConfirm(true);}}>{confirm?'确认死亡':'选择死亡'}</button></section></div>:<button className="down-reminder" onClick={()=>setDismissed(false)}>已倒地 · 等待救援 / 死亡选择</button>}</>;
 if(character.life!=='soul')return null;
 return <section className="life-panel soul-panel"><strong>灵魂回归</strong><p>跑回死亡标记复活，或原地等待回城。</p>{character.timerKind&&<p>回城 · {Math.max(0,Math.ceil((character.timerEnd-clock)/1000))} 秒 <button disabled={busy} onClick={()=>onAction('cancel')}>取消</button></p>}<button onClick={onLocate}>定位死亡标记</button><button disabled={busy||!!character.timerKind} onClick={()=>onAction('recall')}>回城复活 · 5秒</button><button disabled={busy||character.q!==character.deathQ||character.r!==character.deathR} onClick={()=>onAction('revive')}>死亡标记复活</button></section>;
}
