import {useEffect,useState} from 'react';
import {api} from './api';
type Person={id:string;username:string;admin:boolean;lastIp:string|null;lastLogin:string|null};
type Ban={id:string;targetType:string;target:string;targetName:string|null;scope:string;reason:string;expiresAt:string|null;active:boolean};
type Pending={id:string;ownerId:string;username:string;mime:string;size:number};
export function ChatAdministration(){
 const [people,setPeople]=useState<Person[]>([]),[bans,setBans]=useState<Ban[]>([]),[pending,setPending]=useState<Pending[]>([]),[error,setError]=useState(''),[busy,setBusy]=useState(false);
 const [targetType,setTargetType]=useState('account'),[target,setTarget]=useState(''),[scope,setScope]=useState('chat'),[duration,setDuration]=useState('60'),[custom,setCustom]=useState('120'),[reason,setReason]=useState('');
 async function load(){const [p,b,i]=await Promise.all([api<Person[]>('/admin/moderation/accounts'),api<Ban[]>('/admin/bans'),api<Pending[]>('/admin/chat/images')]);setPeople(p);setBans(b);setPending(i);}
 useEffect(()=>{load().catch(e=>setError(e.message));},[]);
 async function action(fn:()=>Promise<unknown>,message:string){setBusy(true);setError('');try{await fn();await load();setError(message);}catch(e){setError((e as Error).message);}finally{setBusy(false);}}
 return <section className="chat-admin"><h3>聊天与封禁管理</h3><p className="subtle">禁言只限制聊天室发送；地图头顶表情仍可使用。</p><button className="soft-button" onClick={()=>void load().catch(e=>setError(e.message))}>刷新管理状态</button>
 <form className="ban-form" onSubmit={e=>{e.preventDefault();void action(()=>api('/admin/bans',{targetType,target,scope,minutes:duration==='permanent'?null:Number(duration==='custom'?custom:duration),reason}),'限制已生效');}}>
 <label>封禁对象<select value={targetType} onChange={e=>{setTargetType(e.target.value);setTarget('');}}><option value="account">账号 ID</option><option value="ip">IP 地址</option></select></label>
 <label>{targetType==='account'?'选择玩家':'IPv4 / IPv6'}{targetType==='account'?<select aria-label="选择玩家" required value={target} onChange={e=>setTarget(e.target.value)}><option value="">请选择玩家</option>{people.filter(p=>!p.admin).map(p=><option key={p.id} value={p.id}>{p.username}</option>)}</select>:<input required value={target} onChange={e=>setTarget(e.target.value)} placeholder="例如 203.0.113.10"/>}</label>
 <label>限制范围<select value={scope} onChange={e=>setScope(e.target.value)}><option value="chat">聊天室禁言</option><option value="game">整个游戏封禁</option></select></label>
 <label>持续时间<select value={duration} onChange={e=>setDuration(e.target.value)}><option value="30">30 分钟</option><option value="60">1 小时</option><option value="1440">1 天</option><option value="10080">7 天</option><option value="permanent">永久</option><option value="custom">自定义分钟</option></select></label>
 {duration==='custom'&&<label>分钟数<input type="number" min={1} max={5256000} required value={custom} onChange={e=>setCustom(e.target.value)}/></label>}<label>原因（可选）<input value={reason} maxLength={200} onChange={e=>setReason(e.target.value)}/></label><button className="danger-button" disabled={busy||!target}>执行{scope==='chat'?'禁言':'封禁'}</button></form>
 <details className="login-ip-list"><summary>查看玩家最近登录 IP</summary>{people.filter(p=>!p.admin).map(p=><div key={p.id}><strong>{p.username}</strong><code>{p.lastIp||'尚未登录'}</code>{p.lastIp&&<button className="soft-button" onClick={()=>{setTargetType('ip');setTarget(p.lastIp!);}}>选用此 IP</button>}</div>)}<p>同一网络可能有多名玩家，IP 限制会同时影响他们。</p></details>
 <div className="ban-list">{bans.map(b=><div className={'ban-row '+(!b.active?'inactive':'')} key={b.id}><div><strong>{b.targetName||b.target}</strong><span>{b.scope==='chat'?'聊天禁言':'游戏封禁'} · {b.expiresAt?new Date(b.expiresAt).toLocaleString('zh-CN')+' 到期':'永久'}{!b.active?' · 已解除或到期':''}</span>{b.reason&&<small>{b.reason}</small>}</div>{b.active&&<button className="soft-button" disabled={busy} onClick={()=>void action(()=>api(`/admin/bans/${b.id}/revoke`,{}),'限制已解除')}>解除</button>}</div>)}</div>
 <h3>换图申请 <span>{pending.length} 项待处理</span></h3>{!pending.length&&<p className="empty">暂无待处理申请。</p>}{pending.map(i=><div className="image-review" key={i.id}><img src={`/api/chat/images/${i.id}`} alt={`${i.username} 的换图申请`}/><div><strong>{i.username}</strong><p>{i.mime==='image/gif'?'GIF 动图':'静态图片'} · {(i.size/1024).toFixed(0)} KB</p><p>批准后删除旧图，历史消息显示“图片已更换”。</p><button className="primary compact" disabled={busy} onClick={()=>void action(()=>api(`/admin/chat/images/${i.id}`,{approve:true}),'已批准换图，旧图已删除')}>批准换图</button><button className="soft-button" disabled={busy} onClick={()=>void action(()=>api(`/admin/chat/images/${i.id}`,{approve:false}),'已拒绝申请，当前图片不变')}>拒绝</button></div></div>)}{error&&<p className="form-note" role="status">{error}</p>}</section>;
}
