import {useCallback,useEffect,useRef,useState} from 'react';
import {MessageCircle,Send,ImagePlus,Smile,ArrowLeft,RefreshCw,X} from 'lucide-react';
import {api,ApiError} from './api';
import {emoteArt} from './emotes';
import {PixelEmote} from './EmotePicker';
import type {Account,Player} from './types';
export type Contact={id:string;username:string;color:string;unread:boolean};
export type ChatImage={id:string;status:'active'|'pending';mime:string;size:number};
export type ChatStatus={publicUnread:boolean;contacts:Contact[];muted:boolean;images:ChatImage[]};
type Message={id:number;senderId:string;username:string;recipientId:string|null;kind:'text'|'emote'|'image';body:string;imageId:string|null;imageAvailable:boolean;createdAt:string};
type History={messages:Message[];hasMore:boolean};
const empty:ChatStatus={publicUnread:false,contacts:[],muted:false,images:[]};
export function useChatStatus(revision:number,onLost:(reason?:string)=>void){
 const [status,setStatus]=useState<ChatStatus>(empty),request=useRef(0),alive=useRef(true),lost=useRef(onLost);lost.current=onLost;
 const refresh=useCallback(async()=>{const id=++request.current;try{const next=await api<ChatStatus>('/chat/status');if(alive.current&&id===request.current)setStatus(next);}catch(e){if(alive.current&&e instanceof ApiError&&[401,403].includes(e.status))lost.current(e.message);}},[]);
 useEffect(()=>{alive.current=true;void refresh();const timer=setInterval(()=>void refresh(),5000);return()=>{alive.current=false;clearInterval(timer);};},[refresh]);
 useEffect(()=>{void refresh();},[revision,refresh]);return{status,refresh};
}
function ChatPicture({id,available}:{id:string|null;available:boolean}){const [failed,setFailed]=useState(false);return !available||!id||failed?<span className="image-expired">图片已更换</span>:<img className="chat-picture" src={`/api/chat/images/${id}`} alt="聊天图片" loading="lazy" onError={()=>setFailed(true)}/>;}
export function ChatPanel({me,status,players,revision,refresh,mode,onMode,peer,onPeer}:{me:Account;status:ChatStatus;players:Player[];revision:number;refresh:()=>Promise<void>;mode:'public'|'private';onMode:(mode:'public'|'private')=>void;peer:string|null;onPeer:(id:string|null)=>void}){
 const contact=status.contacts.find(c=>c.id===peer);
 return <><div className="sidebar-heading chat-heading"><span className="tiny-label">LET THE JOURNEY CONNECT US</span><h2>旅途闲话<MessageCircle size={21}/></h2><p>在同一片天地，聊聊沿途所见。</p></div><div className="chat-tabs"><button className={mode==='public'?'active':''} onClick={()=>onMode('public')}>公聊{status.publicUnread&&<i className="unread-dot" aria-label="公聊有未读消息"/>}</button><button className={mode==='private'?'active':''} onClick={()=>onMode('private')}>私聊{status.contacts.some(c=>c.unread)&&<i className="unread-dot" aria-label="私聊有未读消息"/>}</button></div>
 {mode==='private'&&(!peer||!contact)?<div className="chat-contacts"><p className="chat-help">选择一位旅人，离线时也能留言。</p>{status.contacts.map(c=><button className="place-row" key={c.id} onClick={()=>onPeer(c.id)}><span className="avatar" style={{background:c.color}}>{c.username.slice(0,1)}</span><span><strong>{c.username}</strong><small>{players.some(p=>p.id===c.id&&p.online)?'在线':'离线 · 可以留言'}</small></span>{c.unread&&<i className="unread-dot" aria-label="有未读消息"/>}</button>)}{!status.contacts.length&&<p className="empty">还没有其他获准的旅人。</p>}</div>:<Conversation key={mode==='public'?'public':peer} me={me} status={status} revision={revision} refresh={refresh} peer={mode==='public'?null:peer} name={mode==='public'?'大陆公聊':contact!.username} onBack={mode==='private'?()=>onPeer(null):undefined}/>}
 </>;
}
function Conversation({me,status,revision,refresh,peer,name,onBack}:{me:Account;status:ChatStatus;revision:number;refresh:()=>Promise<void>;peer:string|null;name:string;onBack?:()=>void}){
 const [messages,setMessages]=useState<Message[]>([]),[more,setMore]=useState(false),[draft,setDraft]=useState(''),[error,setError]=useState(''),[busy,setBusy]=useState(false),[older,setOlder]=useState(false),[emotes,setEmotes]=useState(false),[images,setImages]=useState(false),[visible,setVisible]=useState(document.visibilityState==='visible');
 const list=useRef<HTMLDivElement>(null),atBottom=useRef(true),readTo=useRef(0),loaded=useRef(false),mounted=useRef(true),request=useRef(0),imageInput=useRef<HTMLInputElement>(null);
 const query=peer?`?peer=${encodeURIComponent(peer)}`:'';
 const load=useCallback(async()=>{const id=++request.current;try{const page=await api<History>('/chat/messages'+query);if(!mounted.current||id!==request.current)return;setMessages(old=>{const byId=new Map(old.map(m=>[m.id,m]));page.messages.forEach(m=>byId.set(m.id,m));return [...byId.values()].sort((a,b)=>a.id-b.id);});if(!loaded.current){setMore(page.hasMore);loaded.current=true;}}catch(e){if(mounted.current)setError((e as Error).message);}},[query]);
 useEffect(()=>{mounted.current=true;void load();const timer=setInterval(()=>void load(),5000);const onVisibility=()=>setVisible(document.visibilityState==='visible');document.addEventListener('visibilitychange',onVisibility);return()=>{mounted.current=false;clearInterval(timer);document.removeEventListener('visibilitychange',onVisibility);};},[load]);
 useEffect(()=>{void load();},[revision,load]);
 useEffect(()=>{if(atBottom.current)list.current?.scrollTo({top:list.current.scrollHeight});const last=messages.at(-1)?.id||0;if(visible&&last>readTo.current){readTo.current=last;api('/chat/read',{peer,upTo:last}).then(refresh).catch(()=>{readTo.current=0;});}},[messages,visible,peer,refresh]);
 async function loadOlder(){if(!messages.length||older)return;setOlder(true);const previous=list.current?.scrollHeight||0;atBottom.current=false;try{const page=await api<History>('/chat/messages'+query+(query?'&':'?')+'before='+messages[0].id);if(!mounted.current)return;setMessages(old=>{const map=new Map([...page.messages,...old].map(m=>[m.id,m]));return [...map.values()].sort((a,b)=>a.id-b.id);});setMore(page.hasMore);requestAnimationFrame(()=>{if(list.current)list.current.scrollTop+=list.current.scrollHeight-previous;});}catch(e){setError((e as Error).message);}finally{setOlder(false);}}
 async function send(kind:string,body=''){if(busy)return;setBusy(true);setError('');try{await api('/chat/messages',{peer,kind,body});if(kind==='text')setDraft('');setEmotes(false);atBottom.current=true;await load();await refresh();}catch(e){setError((e as Error).message);}finally{setBusy(false);}}
 async function upload(file:File){if(file.size>5*1024*1024){setError('图片最多5MB');return;}setBusy(true);setError('');try{const form=new FormData();form.append('file',file);const res=await fetch('/api/chat/image',{method:'POST',headers:{'X-World-Request':'1'},body:form});const data=await res.json().catch(()=>({message:'上传失败'}));if(!res.ok)throw Error(data.message||'上传失败');setError(data.message);await refresh();}catch(e){setError((e as Error).message);}finally{setBusy(false);if(imageInput.current)imageInput.current.value='';}}
 const active=status.images.find(i=>i.status==='active'),pending=status.images.find(i=>i.status==='pending');
 return <div className="conversation"><div className="conversation-title">{onBack&&<button className="icon-button" aria-label="返回私聊列表" onClick={onBack}><ArrowLeft size={16}/></button>}<strong>{name}</strong><small>{peer?'仅双方可见':'所有获准旅人可见'}</small><button className="icon-button" aria-label="刷新聊天" onClick={()=>void load()}><RefreshCw size={14}/></button></div>
 <div className="chat-history" ref={list} onScroll={()=>{const e=list.current;if(e){atBottom.current=e.scrollHeight-e.scrollTop-e.clientHeight<60;if(e.scrollTop<15&&more)void loadOlder();}}}>
 {more&&<button className="history-more" disabled={older} onClick={()=>void loadOlder()}>{older?'正在读取…':'查看更早消息'}</button>}{!messages.length&&<p className="empty">还没有消息，打个招呼吧。</p>}
 {messages.map(m=><article key={m.id} className={'chat-message '+(m.senderId===me.id?'own':'')}><div className="chat-meta"><strong>{m.username}</strong><time dateTime={m.createdAt}>{new Date(m.createdAt).toLocaleString('zh-CN',{month:'numeric',day:'numeric',hour:'2-digit',minute:'2-digit'})}</time></div><div className={'message-content '+m.kind}>{m.kind==='text'?m.body:m.kind==='emote'?<span role="img" aria-label={emoteArt.find(e=>e.code===m.body)?.name||'表情'}><PixelEmote code={m.body}/></span>:<ChatPicture id={m.imageId} available={m.imageAvailable}/>}</div></article>)}</div>
 {images&&<div className="image-manager"><div className="image-manager-title"><strong>我的图片位</strong><button className="icon-button" aria-label="关闭图片管理" onClick={()=>setImages(false)}><X size={14}/></button></div><p>JPG / PNG / GIF · 最多5MB<br/>{active?'换图需审批，通过后历史旧图会移除。':'首次添加可直接使用，以后换图需审批。'}</p>{active&&<div className="current-image"><img src={`/api/chat/images/${active.id}`} alt="当前可发送图片"/><button className="soft-button" disabled={busy||status.muted} onClick={()=>void send('image')}>发送当前图片</button></div>}{pending&&<p className="pending-image">换图申请等待审批，当前图片仍可发送。</p>}<input ref={imageInput} type="file" accept="image/jpeg,image/png,image/gif" aria-label={active?'选择换图申请图片':'选择首次上传图片'} disabled={busy||status.muted||!!pending} onChange={e=>{const file=e.target.files?.[0];if(file)void upload(file);}}/></div>}
 {emotes&&<div className="chat-emotes" role="group" aria-label="聊天表情">{emoteArt.map(e=><button key={e.code} title={e.name} aria-label={`聊天发送${e.name}`} disabled={busy||status.muted} onClick={()=>void send('emote',e.code)}><PixelEmote code={e.code}/><span>{e.name}</span></button>)}</div>}
 <form className="chat-composer" onSubmit={e=>{e.preventDefault();void send('text',draft);}}><div className="chat-toolbar"><button type="button" className="icon-button" aria-label="选择聊天表情" title="表情" disabled={status.muted} onClick={()=>{setEmotes(v=>!v);setImages(false);}}><Smile size={18}/></button><button type="button" className="icon-button" aria-label="管理聊天图片" title="图片" onClick={()=>{setImages(v=>!v);setEmotes(false);}}><ImagePlus size={18}/></button><small>{status.muted?'当前已被禁言，仍可阅读消息':'聊聊此刻，不必赶路'}</small></div><textarea aria-label="聊天消息" placeholder={status.muted?'禁言期间暂时不能发送':'写一条消息…'} maxLength={1000} value={draft} disabled={status.muted} onChange={e=>setDraft(e.target.value)}/><div className="chat-send-row">{error&&<span role="status" className="chat-error">{error}</span>}<button className="primary compact" disabled={busy||status.muted||!draft.trim()}><Send size={14}/>{busy?'处理中':'发送'}</button></div></form></div>;
}
