import React, { useCallback, useEffect, useRef, useState } from 'react';
import { createRoot } from 'react-dom/client';
import { Compass, Map as MapIcon, Users, Shield, LogOut, ArrowRight, TreePine, Mountain, Waves, Home, Landmark, Plus, Minus, LocateFixed, Expand, X, Check, ChevronRight, Footprints, LoaderCircle, RefreshCw, Square, Leaf, KeyRound, LockKeyhole, Backpack, MessageCircle, PanelLeftClose, PanelLeftOpen, Swords } from 'lucide-react';
import { api, ApiError } from './api';
import {ChatPanel,useChatStatus} from './Chat';
import {ChatAdministration} from './ChatAdministration';
import { EmotePicker } from './EmotePicker';
import { MapView } from './MapView';
import { BattleView } from './BattleView';
import type { MapControls } from './MapView';
import type { Account, Hex, Player, State, Tile, World, Item, ResourceNode, WorldAction, Emote, BattleSummary, BattleState } from './types';
import { key, terrainNames, placeNames, walkable } from './types';
import './style.css';
import './viewport.css';
import './battle.css';

function Brand(){return <div className="brand"><span className="brand-mark"><TreePine size={22}/></span><div><strong>青屿</strong><span>一方天地，万种旅途</span></div></div>}
function IslandArt(){return <svg viewBox="0 0 620 540" className="island-art" aria-label="像素风大陆插画" role="img"><defs><pattern id="waves" width="52" height="48" patternUnits="userSpaceOnUse"><path d="M6 28h12m4 3h7" stroke="#baddd9" strokeWidth="2"/></pattern><g id="pine"><path d="M-3 0h6v16h-6" fill="#7a7155"/><path d="M-18-6h36v-8h-5v-9h-6v-9H-7v9h-6v9h-5z" fill="#5e8865"/><path d="M-7-30h7v13H-7v9h-9v-6h5v-9h4z" fill="#83a572"/></g><g id="home"><path d="M-23-4h46v33h-46z" fill="#f4e6b8"/><path d="M-29-9h58v-7h-7v-7h-8v-7h-9v-7H-5v7h-9v7h-8v7h-7z" fill="#bd8058"/><path d="M-5 11h10v18H-5M-18 5h7v8h-7m29-8h7v8h-7" fill="#6d7970"/></g></defs><rect width="620" height="540" fill="url(#waves)"/><path d="M104 195h34v-52h52v-29h84V84h87v27h51v37h56v41h40v79h-25v64h-46v47h-63v47h-79v-21h-66v-32h-78v-35h-42v-67H84v-43h20z" fill="#7ea9a0" opacity=".3" transform="translate(0,14)"/><path d="M104 195h34v-52h52v-29h84V84h87v27h51v37h56v41h40v79h-25v64h-46v47h-63v47h-79v-21h-66v-32h-78v-35h-42v-67H84v-43h20z" fill="#e4d8a7"/><path d="M117 203h35v-47h48v-28h85v-29h65v28h50v36h53v37h42v57h-26v67h-43v43h-62v45h-58v-22h-65v-29h-77v-36h-40v-62H98v-24h19z" fill="#b7cc8b"/><path d="M305 103v66h-22v65h28v63h-18v51h36v59" fill="none" stroke="#90c1c1" strokeWidth="16"/><path d="M177 261h64v-29h132v56h53" fill="none" stroke="#e8d5a0" strokeWidth="13"/><path d="M278 222h44v20h-44z" fill="#ad8b59"/><path d="M280 226h40m-40 10h40" stroke="#ead1a0" strokeWidth="3"/><use href="#pine" x="200" y="194"/><use href="#pine" x="164" y="216"/><use href="#pine" x="231" y="171"/><use href="#pine" x="388" y="217"/><use href="#pine" x="423" y="247"/><use href="#pine" x="384" y="352"/><use href="#home" x="235" y="275"/><use href="#home" x="356" y="187"/><path d="M237 341h30m-26-8h26m-29-8h28" stroke="#d9be76" strokeWidth="5"/><path d="M179 315h8v8h-8m-17-7h5v5h-5m219-15h8v8h-8" fill="#e9e8bd"/><text x="310" y="476" textAnchor="middle" fill="#5e8f8e" fontSize="12" letterSpacing="8">每一段旅途，都从这里开始</text></svg>}

function App(){
  const [me,setMe]=useState<Account|null>(null),[loading,setLoading]=useState(true),[error,setError]=useState('');
  const [register,setRegister]=useState(false),[busy,setBusy]=useState(false),[notice,setNotice]=useState('');
  useEffect(()=>{api<Account>('/me').then(setMe).catch(e=>{if(!(e instanceof ApiError&&e.status===401))setError(e.message);}).finally(()=>setLoading(false));},[]);
  const logout=async()=>{try{await api('/logout',{});setMe(null);}catch(e){setError((e as Error).message);}};
  if(loading)return <div className="loading-screen"><Brand/><LoaderCircle className="spin"/><p>正在连接青屿大陆…</p></div>;
  if(me?.approved)return <Game me={me} onLogout={logout} onAccessLost={(reason)=>{if(reason)setError(reason);api<Account>('/me').then(setMe).catch(()=>setMe(null));}}/>;
  if(me)return <div className="gate"><Brand/><div className="pending-card"><span className="big-icon"><Leaf size={38}/></span><p className="eyebrow">旅途即将开始</p><h1>你好，{me.username}</h1><p>你的账号正在等待管理员批准。<br/>获准后，就能和其他旅人一起探索大陆。</p><button className="primary" disabled={busy} onClick={async()=>{setBusy(true);try{const a=await api<Account>('/me');setMe(a);setNotice(a.approved?'':'暂未获准，请稍后再来');}catch{setMe(null);}finally{setBusy(false);}}}><RefreshCw size={16}/>查看审批状态</button>{notice&&<p role="status" className="form-note">{notice}</p>}<button className="text-button" onClick={logout}>退出账号</button></div><span className="gate-footer">青屿 · 大世界探索试玩</span></div>;
  async function submit(e:React.SubmitEvent<HTMLFormElement>){
    e.preventDefault();setError('');setNotice('');setBusy(true);const f=new FormData(e.currentTarget),credentials={username:String(f.get('username')).trim(),password:String(f.get('password'))};
    try{if(register){await api('/register',credentials);setNotice('申请已提交。请登录查看审批状态。');setRegister(false);}else setMe(await api<Account>('/login',credentials));}catch(e){setError((e as Error).message);}finally{setBusy(false);}
  }
  return <div className="auth-layout"><section className="auth-art"><Brand/><div className="art-copy"><p className="eyebrow">一张地图，一场共同的冒险</p><h1>远方有路，<br/>此刻出发。</h1><p>穿过林间，沿着河岸，遇见同路的旅人。</p></div><IslandArt/><div className="art-foot"><span>六角天地 · 自由探索</span><span>青屿大陆 / 01</span></div></section><section className="auth-form-wrap"><div className="auth-form"><span className="tiny-label">WELCOME TO QINGYU</span><h2>{register?'成为一名旅人':'欢迎回到青屿'}</h2><p className="subtle">{register?'注册账号，申请进入这片共同的世界。':'登录账号，接着走完未完的旅途。'}</p><div className="auth-tabs"><button className={!register?'active':''} onClick={()=>{setRegister(false);setError('');}}>账号登录</button><button className={register?'active':''} onClick={()=>{setRegister(true);setError('');}}>申请加入</button></div><form onSubmit={submit}><label>用户名<input name="username" required minLength={2} maxLength={24} autoComplete="username" placeholder="你的旅人名字"/></label><label>密码<input name="password" type="password" required minLength={register?10:1} maxLength={72} autoComplete={register?'new-password':'current-password'} placeholder={register?'至少 10 位字符':'输入你的密码'}/></label>{error&&<div className="form-error" role="alert">{error}</div>}{notice&&<div className="form-note" role="status">{notice}</div>}<button className="primary full" disabled={busy}>{busy?<LoaderCircle size={18} className="spin"/>:register?'提交加入申请':'进入青屿大陆'}{!busy&&<ArrowRight size={18}/>}</button></form><p className="auth-hint"><LockKeyhole size={14}/>{register?'账号经管理员批准后，即可进入游戏。':'忘记密码？请联系管理员重置。'}</p></div><span className="auth-footer">慢一点，世界值得探索。</span></section></div>;
}

function Game({me,onLogout,onAccessLost}:{me:Account;onLogout:()=>void;onAccessLost:(reason?:string)=>void}){
  const [world,setWorld]=useState<World|null>(null),[players,setPlayers]=useState<Player[]>([]),[selected,setSelected]=useState<Tile|null>(null),[route,setRoute]=useState<Hex[]>([]);
  const [tab,setTab]=useState<'places'|'players'|'inventory'|'chat'>('places'),[sidebarOpen,setSidebarOpen]=useState(true),[filter,setFilter]=useState('all'),[zoom,setZoom]=useState(100),[connected,setConnected]=useState(false),[message,setMessage]=useState(''),[admin,setAdmin]=useState(false),[loading,setLoading]=useState(true);
  const [chatRevision,setChatRevision]=useState(0),[chatMode,setChatMode]=useState<'public'|'private'>('public'),[chatPeer,setChatPeer]=useState<string|null>(null);
  const {status:chatStatus,refresh:refreshChat}=useChatStatus(chatRevision,onAccessLost);
  const showTab=(next:'places'|'players'|'inventory'|'chat')=>{if(tab===next)setSidebarOpen(open=>!open);else{setTab(next);setSidebarOpen(true);}};
  const openPrivate=(id:string)=>{setChatPeer(id);setChatMode('private');setTab('chat');setSidebarOpen(true);};
  const [emotes,setEmotes]=useState<Emote[]>([]);
  const [items,setItems]=useState<Item[]>([]),[resources,setResources]=useState<ResourceNode[]>([]),[actions,setActions]=useState<WorldAction[]>([]),[clock,setClock]=useState(Date.now()),[collecting,setCollecting]=useState(false);
  const [battle,setBattle]=useState<BattleState>({active:false}),[battles,setBattles]=useState<BattleSummary[]>([]),[view,setView]=useState<'world'|'battle'>('world');
  const battleRef=useRef<BattleState>({active:false}),battleRevision=useRef(-1),battleRequest=useRef(0);
  const refreshBattle=useCallback(async()=>{const request=++battleRequest.current;const next=await api<BattleState>('/battle/current');if(request!==battleRequest.current)return;const previous=battleRef.current;battleRef.current=next;setBattle(next);if(next.active&&!previous.active)setView('battle');if(!next.active&&previous.active){setView('world');setMessage('同格战斗已结束，返回大世界');}},[]);
  const offset=useRef(0),resourceSignature=useRef(''),previousItems=useRef<Item[]|null>(null);
  const applyInventory=(next:Item[])=>{if(previousItems.current){const gained=next.map(i=>({name:i.name,quantity:i.quantity-(previousItems.current!.find(old=>old.code===i.code)?.quantity||0)})).filter(i=>i.quantity>0);if(gained.length)setMessage(gained.map(i=>`${i.name} +${i.quantity}`).join(' · '));}previousItems.current=next;setItems(next);};
  useEffect(()=>{const timer=setInterval(()=>setClock(Date.now()+offset.current),100);return()=>clearInterval(timer);},[]);
  const controls=useRef<MapControls|null>(null),worldRef=useRef<World|null>(null),lastVersion=useRef('');
  const reload=useCallback(async()=>{const data=await api<World>('/world');worldRef.current=data;lastVersion.current=data.version;setWorld(data);setRoute([]);setSelected(null);},[]);
  useEffect(()=>{let alive=true;reload().catch(e=>{if(alive)setMessage(e.message);}).finally(()=>{if(alive)setLoading(false);});return()=>{alive=false;};},[reload]);
  useEffect(()=>{void refreshBattle().catch(e=>setMessage(e.message));},[refreshBattle]);
  useEffect(()=>{
    if(!world)return;
    let alive=true,socket:WebSocket|null=null,timer:ReturnType<typeof setTimeout>|null=null,attempt=0;
    function connect(){
      socket=new WebSocket(`${location.protocol==='https:'?'wss':'ws'}://${location.host}/ws`);
      socket.onopen=()=>{if(alive){setConnected(true);attempt=0;resourceSignature.current='';void refreshBattle().catch(e=>setMessage(e.message));}};
      socket.onmessage=e=>{if(!alive)return;const data=JSON.parse(e.data);if(data.type==='chat-changed'){setChatRevision(v=>v+1);return;}if(data.type!=='state')return;const state=data as State;
        if(data.version!==lastVersion.current){lastVersion.current=data.version;setMessage('世界已重新生成，正在返回新的出生点');reload().catch(e=>setMessage(e.message));}
        offset.current=data.serverTime-Date.now();setClock(data.serverTime);setResources(data.resources);setActions(data.actions);setEmotes(data.emotes||[]);setBattles(state.battles||[]);
        if(state.battleRevision!==battleRevision.current){battleRevision.current=state.battleRevision;void refreshBattle().catch(e=>setMessage(e.message));}
        const signature=JSON.stringify(data.resources);if(signature!==resourceSignature.current){resourceSignature.current=signature;api<Item[]>('/inventory').then(v=>{if(alive)applyInventory(v);}).catch(e=>{if(alive){if(resourceSignature.current===signature)resourceSignature.current='';setMessage(e.message);}});}
        setPlayers(state.players);const own=state.players.find(p=>p.id===me.id);if(own)setRoute(old=>{const i=old.findIndex(h=>h.q===own.q&&h.r===own.r);return own.moving?(i>=0?old.slice(i+1):old):[];});
      };
      socket.onclose=()=>{if(!alive)return;setConnected(false);api<Account>('/me').then(a=>{if(!a.approved){onAccessLost();return;}timer=setTimeout(connect,Math.min(10000,1000*2**attempt++));}).catch(e=>{if(e instanceof ApiError&&[401,403].includes(e.status))onAccessLost(e.message);else timer=setTimeout(connect,5000);});};
      socket.onerror=()=>socket?.close();
    }
    connect();return()=>{alive=false;if(timer)clearTimeout(timer);socket?.close();};
  },[!!world,me.id,refreshBattle]);
  const own=players.find(p=>p.id===me.id),online=players.filter(p=>p.online);
  const choose=(tile:Tile)=>setSelected(tile);
  async function travel(){if(!selected||!world||battle.active)return;try{const data=await api<{path:Hex[]}>('/move',{q:selected.q,r:selected.r,version:world.version});setRoute(data.path);setMessage(data.path.length?`前往${selected.place?.name||terrainNames[selected.terrain]} · ${data.path.length} 格`:'你已在这里');}catch(e){setMessage((e as Error).message);}}
  const resource=selected?resources.find(n=>key(n)===key(selected)):undefined;
  const currentAction=resource?actions.find(a=>a.nodeId===resource.id):undefined;
  const ownAction=actions.find(a=>a.accountId===me.id);
  const atResource=!!own&&!!selected&&key(own)===key(selected)&&!own.moving;
  async function collect(){if(!selected||!world||battle.active)return;setCollecting(true);try{const result=await api<{message:string}>('/collect',{...{q:selected.q,r:selected.r},version:world.version});setMessage(result.message);applyInventory(await api<Item[]>('/inventory'));}catch(e){setMessage((e as Error).message);}finally{setCollecting(false);}}
  async function startBattle(targetId:string){if(!world)return;try{await api('/battle/start',{targetId,version:world.version});await refreshBattle();setSidebarOpen(false);}catch(e){setMessage((e as Error).message);}}
  async function joinBattle(id:string){if(!world)return;try{await api('/battle/join',{battleId:id,version:world.version});await refreshBattle();setSidebarOpen(false);}catch(e){setMessage((e as Error).message);}}
  const landmarks=world?.tiles.filter(t=>t.place&&(filter==='all'||t.place.type===filter))||[];
  const here=selected?players.filter(p=>key(p)===key(selected)):[];
  const openBattle=selected?battles.find(b=>key(b)===key(selected)):undefined;
  return <div className={'game-shell '+(sidebarOpen?'sidebar-open':'sidebar-closed')}><header className="topbar"><Brand/><div className="world-heading"><span>{battle.active&&view==='battle'?'局部战斗':'世界探索'}</span><span className="divider"/><span>青屿大陆</span><span className="version-badge">探索试玩</span></div><div className="top-actions">{battle.active&&<button className="view-switch" aria-label={view==='world'?'切换到战斗地图':'切换到大世界地图'} onClick={()=>setView(current=>current==='world'?'battle':'world')}>{view==='world'?<Swords size={16}/>:<MapIcon size={16}/ >}{view==='world'?'查看战场':'查看大世界'}</button>}<span className={'connection '+(connected?'':'disconnected')}><i/>{connected?`${online.length} 位旅人在线`:'正在重新连接'}</span><span className="avatar" style={{background:me.color}}>{me.username.slice(0,1)}</span><span className="username">{me.username}</span><button className="icon-button" title="退出登录" aria-label="退出登录" onClick={onLogout}><LogOut size={17}/></button></div></header>
    <div className="workspace"><nav className="rail"><button aria-label={sidebarOpen?'收起侧栏':'展开侧栏'} title={sidebarOpen?'收起侧栏':'展开侧栏'} onClick={()=>setSidebarOpen(open=>!open)}>{sidebarOpen?<PanelLeftClose size={21}/>:<PanelLeftOpen size={21}/>}</button><button className={sidebarOpen&&tab==='places'?'active':''} aria-label="地点目录" title="地点目录" onClick={()=>showTab('places')}><MapIcon size={22}/></button><button className={sidebarOpen&&tab==='players'?'active':''} aria-label="旅人列表" title="旅人列表" onClick={()=>showTab('players')}><Users size={21}/></button><button className={sidebarOpen&&tab==='inventory'?'active':''} aria-label="背包" title="背包" onClick={()=>showTab('inventory')}><Backpack size={21}/></button><button className={'chat-rail-button '+(sidebarOpen&&tab==='chat'?'active':'')} aria-label="聊天室" title="聊天室" onClick={()=>showTab('chat')}><MessageCircle size={21}/>{(chatStatus.publicUnread||chatStatus.contacts.some(c=>c.unread))&&<i className="unread-dot" aria-label="聊天有未读消息"/>}</button><div className="rail-spacer"/>{me.admin&&<button title="管理后台" aria-label="管理后台" onClick={()=>setAdmin(true)}><Shield size={21}/></button>}<span className="rail-leaf"><Leaf size={18}/></span></nav>
    <aside className={'sidebar '+(tab==='chat'?'chat-sidebar':'')+(sidebarOpen?'':' collapsed')} aria-hidden={!sidebarOpen}>{tab==='chat'?<ChatPanel me={me} status={chatStatus} players={players} revision={chatRevision} refresh={refreshChat} mode={chatMode} onMode={setChatMode} peer={chatPeer} onPeer={setChatPeer}/>:<><div className="sidebar-heading"><span className="tiny-label">{tab==='places'?'THE WORLD AT A GLANCE':tab==='inventory'?'YOUR BELONGINGS':'FELLOW TRAVELERS'}</span><h2>{tab==='places'?'大陆手记':tab==='inventory'?'背包':'同行旅人'}<span>{tab==='places'?world?.tiles.filter(t=>t.place).length||'—':tab==='inventory'?items.filter(i=>i.quantity>0).length:players.length}</span></h2><p>{tab==='places'?'选一处目的地，让好奇心带路。':tab==='inventory'?'沿途所得，妥善收好。':'每个名字，都是另一段旅途。'}</p></div>
      {tab==='places'?<><div className="filters">{[['all','全部'],['town','城镇'],['village','村庄'],['ruin','遗迹']].map(([id,label])=><button key={id} onClick={()=>setFilter(id)} className={filter===id?'active':''}>{label}</button>)}</div><div className="place-list">{landmarks.map(t=><button className={'place-row '+(selected&&key(selected)===key(t)?'selected':'')} key={key(t)} onClick={()=>{choose(t);controls.current?.locate(t);}}><span className={'place-icon '+t.place!.type}>{t.place!.type==='ruin'?<Landmark size={20}/>:<Home size={20}/>}</span><span><strong>{t.place!.name}{key(t)===key(world!.spawn)&&<em>起点</em>}</strong><small>{placeNames[t.place!.type]} <span>·</span> {t.q}, {t.r}</small></span><ChevronRight size={15}/></button>)}</div><div className="sidebar-note"><Compass size={23}/><div><strong>不必赶路</strong><p>这里没有行动点限制。<br/>沿途的风景，也值得停留。</p></div></div></>:tab==='inventory'?<div className="place-list inventory-list">{items.map(i=><div className="place-row" key={i.code}><span className="place-icon">{i.code==='wood'?<TreePine size={21}/>:<Mountain size={21}/>}</span><span><strong>{i.name}</strong><small>采集材料</small></span><b className="item-quantity">× {i.quantity}</b></div>)}<p className="empty">同类物品自动叠加 · 暂无容量限制</p></div>:<div className="place-list">{players.map(p=><div className="traveler-row" key={p.id}><button className="place-row" onClick={()=>{const t=world?.tiles.find(t=>key(t)===key(p));if(t)choose(t);controls.current?.locate(p);}}><span className="avatar" style={{background:p.online?p.color:'#a7ada8'}}>{p.username.slice(0,1)}</span><span><strong>{p.username}{p.id===me.id&&<em>你</em>}</strong><small>{p.online?'在线':'离线'} · {p.q}, {p.r}</small></span><i className={'status-dot '+(p.online?'online':'')}/></button>{p.id!==me.id&&<button className="traveler-chat icon-button" title={`私聊 ${p.username}`} aria-label={`私聊 ${p.username}`} onClick={()=>openPrivate(p.id)}><MessageCircle size={15}/></button>}</div>)}{!players.length&&<p className="empty">连接后将在这里显示旅人。</p>}</div>}
    </>}</aside>
    <main className={'map-surface '+(battle.active&&view==='battle'?'show-battle':'')}>{world&&<MapView world={world} emotes={emotes} resources={resources} actions={actions} clockOffset={offset.current} players={players} me={me.id} selected={selected} route={route} onSelect={choose} onZoom={setZoom} controls={controls}/>}
      {battle.active&&view==='battle'&&<BattleView battle={battle} me={me.id} connected={connected} clock={clock} onChanged={refreshBattle} onMessage={setMessage}/>}
      {battle.active&&view==='world'&&<div className="battle-world-note" role="status">角色正在战斗中 · 大世界仅供查看</div>}
      {loading&&<div className="map-loading"><LoaderCircle className="spin"/>正在展开大陆地图…</div>}
      {!world&&!loading&&<div className="map-loading"><p>{message||'地图暂时无法载入'}</p><button className="primary" onClick={()=>{setLoading(true);reload().catch(e=>setMessage(e.message)).finally(()=>setLoading(false));}}>重新加载</button></div>}
      <div className="map-title"><span className="map-title-icon"><Compass size={20}/></span><div><strong>{world?.name||'青屿大陆'}</strong><small>全境地图 <span>·</span> 自由探索</small></div></div>
      <div className="compass" aria-hidden="true"><span>N</span><svg viewBox="0 0 50 50"><path d="M25 4L33 34 25 28 17 34Z" fill="#446d64"/><path d="M25 4v24l-8 6z" fill="#faf6df"/></svg></div>
      <div className="map-tools"><button aria-label="放大地图" title="放大" onClick={()=>controls.current?.zoom(1.3)}><Plus size={19}/></button><span>{zoom}%</span><button aria-label="缩小地图" title="缩小" onClick={()=>controls.current?.zoom(1/1.3)}><Minus size={19}/></button><hr/><button aria-label="查看全图" title="查看全图" onClick={()=>controls.current?.fit()}><Expand size={18}/></button><button aria-label="定位自己" title="定位自己" onClick={()=>controls.current?.locate(own||me)}><LocateFixed size={19}/></button></div>
      {selected&&<section className="location-card"><div className="location-heading"><span className="place-icon">{selected.place?<Home size={23}/>:selected.terrain==='forest'?<TreePine size={23}/>:['river','ocean','bridge'].includes(selected.terrain)?<Waves size={23}/>:<Mountain size={23}/>}</span><div><span className="tiny-label">{selected.place?placeNames[selected.place.type]:terrainNames[selected.terrain]} · {selected.q}, {selected.r}</span><h3>{selected.place?.name||terrainNames[selected.terrain]}</h3></div><button aria-label="关闭地点详情" className="icon-button" onClick={()=>setSelected(null)}><X size={17}/></button></div><p>{selected.place?.description||(walkable(selected)?'这片土地可以通行。选择前往，看看沿途的风景。':'这里无法直接通行。寻找道路或桥梁，绕行到另一侧。')}</p>{here.length>0&&<div className="occupants"><Users size={14}/>{here.map(p=>p.username+(p.online?'':'（离线）')).join('、')}</div>}{resource&&<div className="resource-detail"><strong>{resource.kind==='stone'?'散落的小石头':resource.readyAt>0?'树桩 · 等待新生':'可砍伐的森林'}</strong>{resource.readyAt>0?<p>{resource.kind==='wood'?`树木恢复：${Math.max(0,Math.ceil((resource.readyAt-clock)/1000))} 秒`:'石头已捡走，稍后将在随机平原补充。'}</p>:currentAction?<p>{currentAction.accountId===me.id?'正在砍伐':`${players.find(p=>p.id===currentAction.accountId)?.username||'旅人'} 正在砍伐`} · {Math.max(0,Math.ceil((currentAction.endsAt-clock)/1000))} 秒</p>:atResource?<button className="primary full" disabled={!connected||collecting||!!ownAction} onClick={collect}>{resource.kind==='stone'?'捡拾 · 石头 +1':'砍伐 · 木头 +1'}</button>:<p>到达此格后可以{resource.kind==='stone'?'捡拾':'砍伐'}。</p>}</div>}<button className="primary full" disabled={!walkable(selected)||!connected} onClick={travel}><Footprints size={16}/>{own&&key(own)===key(selected)?'你已在这里':walkable(selected)?'前往这里':'不可直接通行'}<ArrowRight size={17}/></button></section>}
      {selected&&own&&!battle.active&&!own.moving&&key(selected)===key(own)&&(openBattle||here.some(p=>p.id!==me.id))&&<section className="world-battle-card"><span className="tiny-label">SAME WORLD CELL</span><h3>{openBattle?'此格已有战斗':'同格旅人'}</h3>{openBattle?<><p>{openBattle.participants} 人在战场内。加入后从下一轮开始行动。</p><button className="primary full" disabled={!connected} onClick={()=>void joinBattle(openBattle.id)}><Swords size={16}/>加入战斗</button></>:here.filter(p=>p.id!==me.id).map(p=><button className="world-battle-target" key={p.id} disabled={!connected} onClick={()=>void startBattle(p.id)}><span className="avatar" style={{background:p.color}}>{p.username.slice(0,1)}</span><span>{p.username}<small>{p.online?'在线':'离线 · 可发起战斗'}</small></span><Swords size={16}/></button>)}</section>}
      {world&&<EmotePicker disabled={!connected||battle.active} onSend={async code=>{try{await api('/emote',{code,version:world.version});}catch(e){setMessage((e as Error).message);}}}/>}
      <div className="map-bottom"><div className="legend"><span><i style={{background:'#abc781'}}/>平原</span><span><i style={{background:'#628b63'}}/>森林</span><span><i style={{background:'#909d8b'}}/>山地</span><span><i style={{background:'#80b7c0'}}/>河流</span><span><i style={{background:'#dbca91'}}/>道路</span></div><div className="position-pill"><LocateFixed size={14}/>当前位置 <b>{own?.q??me.q}, {own?.r??me.r}</b>{own?.moving&&<button title="停止移动" aria-label="停止移动" onClick={()=>api('/stop',{}).catch(e=>setMessage(e.message))}><Square size={12}/></button>}</div></div>
      {message&&world&&<div className="toast" role="status">{message}<button className="icon-button" aria-label="关闭提示" onClick={()=>setMessage('')}><X size={14}/></button></div>}
    </main></div><footer className="statusbar"><span><i className="status-dot online"/>同一片大陆，共同探索</span><span>拖动平移 <b>·</b> 滚轮缩放 <b>·</b> 点击地块查看与前往</span><span>青屿 / 探索版 0.1</span></footer>
    {admin&&<Admin onClose={()=>setAdmin(false)} onRegenerate={reload}/>}
  </div>;
}

function Admin({onClose,onRegenerate}:{onClose:()=>void;onRegenerate:()=>Promise<void>}){
  const [accounts,setAccounts]=useState<Account[]>([]),[message,setMessage]=useState(''),[busy,setBusy]=useState(false),[target,setTarget]=useState<Account|null>(null),[password,setPassword]=useState(''),[confirm,setConfirm]=useState('');
  const [bag,setBag]=useState<{account:Account;items:Item[]}|null>(null);
  const bagRequest=useRef(0);
  async function showBag(a:Account){const request=++bagRequest.current;try{const items=await api<Item[]>(`/admin/accounts/${a.id}/inventory`);if(request===bagRequest.current)setBag({account:a,items});}catch(e){setMessage((e as Error).message);}}
  const load=()=>api<Account[]>('/admin/accounts').then(setAccounts);
  useEffect(()=>{load().catch(e=>setMessage(e.message));const keydown=(e:KeyboardEvent)=>{if(e.key==='Escape')onClose();};window.addEventListener('keydown',keydown);return()=>window.removeEventListener('keydown',keydown);},[]);
  async function action(work:()=>Promise<unknown>,success:string){setBusy(true);setMessage('');try{await work();await load();setMessage(success);}catch(e){setMessage((e as Error).message);}finally{setBusy(false);}}
  return <div className="modal-backdrop"><section className="admin-modal" role="dialog" aria-modal="true" aria-labelledby="admin-title"><header><div><span className="tiny-label">WORLD ADMINISTRATION</span><h2 id="admin-title"><Shield size={23}/>世界管理</h2></div><button className="icon-button" aria-label="关闭管理后台" onClick={onClose}><X/></button></header><div className="admin-content"><h3>旅人准入 <span>{accounts.filter(a=>!a.approved).length} 位等待批准</span></h3><p className="subtle">批准新旅人加入，或管理已有账号的游戏权限。</p><div className="account-table">{accounts.map(a=><div className="account-row" key={a.id}><span className="avatar" style={{background:a.color}}>{a.username.slice(0,1)}</span><div><strong>{a.username}</strong><small>{a.admin?'管理员':a.approved?'已获准进入':'等待批准 / 已撤销'}</small></div><button className="soft-button" onClick={()=>showBag(a)}><Backpack size={14}/>查看背包</button>{!a.admin&&<><button className="soft-button" disabled={busy} onClick={()=>{setTarget(a);setPassword('');}}><KeyRound size={14}/>重置密码</button><button className={a.approved?'danger-button':'primary compact'} disabled={busy} onClick={()=>action(()=>api(`/admin/accounts/${a.id}/approval`,{approved:!a.approved}),a.approved?'权限已撤销，玩家已退出':'已批准进入游戏')}>{a.approved?'撤销权限':<><Check size={14}/>批准</>}</button></>}</div>)}</div>
    {bag&&<section className="admin-bag"><h3>{bag.account.username} 的背包</h3>{bag.items.map(i=><div className="bag-line" key={i.code}><span>{i.name}</span><b>× {i.quantity}</b></div>)}<button className="soft-button" onClick={()=>showBag(bag.account)}>刷新背包</button><button className="soft-button" onClick={()=>{bagRequest.current++;setBag(null);}}>关闭</button></section>}
    {target&&<form className="reset-password" onSubmit={e=>{e.preventDefault();action(async()=>{await api(`/admin/accounts/${target.id}/password`,{password});setTarget(null);setPassword('');},'密码已重置，请将新密码告知玩家');}}><label>为 {target.username} 设置新密码<input type="password" value={password} onChange={e=>setPassword(e.target.value)} minLength={10} maxLength={72} required autoComplete="new-password" placeholder="至少10位字符"/></label><button className="primary compact" disabled={busy}>保存新密码</button><button type="button" className="soft-button" onClick={()=>setTarget(null)}>取消</button></form>}
    <ChatAdministration/><section className="danger-zone"><h3>重新生成世界</h3><p>旧地图将被替换，所有角色回到新世界的出生点。账号、审批权限与背包保留，正在进行的采集将取消，此操作无法撤销。</p><form onSubmit={e=>{e.preventDefault();action(async()=>{await api('/admin/regenerate',{confirmation:confirm});setConfirm('');await onRegenerate();},'新世界已生成，所有角色已返回出生点');}}><input aria-label="重建确认文字" value={confirm} onChange={e=>setConfirm(e.target.value)} placeholder="输入：重新生成世界"/><button className="danger-button" disabled={busy||confirm!=='重新生成世界'}>确认重建</button></form></section>{message&&<div className="form-note" role="status">{message}</div>}</div></section></div>;
}

createRoot(document.getElementById('root')!).render(<App/>);
