import pg from 'pg';import {readFileSync,writeFileSync} from 'node:fs';import {randomBytes,randomUUID} from 'node:crypto';import assert from 'node:assert/strict';
const db=new pg.Client({host:'127.0.0.1',port:55432,user:'worldgame',database:'worldgame'});await db.connect();const file=new URL('../.local/character-restart.json',import.meta.url),mode=process.argv[2];
async function snapshot(ids,battle){return {characters:(await db.query('select id,hp,down_hp,life,weapon,bind_q,bind_r,death_q,death_r from characters where id=any($1::uuid[]) order by id',[ids])).rows,actors:(await db.query('select account_id,q,r,initiative,initiative_roll,initiative_score,entry_round from battle_actors where encounter_id=$1 order by initiative',[battle])).rows,intents:(await db.query('select attacker_id,q,r,cells,weapon,damage,min_range,max_range,move_rule,origin_q,origin_r from battle_intents where encounter_id=$1',[battle])).rows,battle:(await db.query('select round_number,turn_account_id,turn_points from battle_encounters where id=$1',[battle])).rows};}
try{if(mode==='prepare'){
 const ids=[];for(let i=0;i<3;i++){const username='restart_life_'+Date.now().toString(36)+'_'+i;const res=await fetch('http://127.0.0.1:8080/api/register',{method:'POST',headers:{Origin:'http://127.0.0.1:5173','X-World-Request':'1','Content-Type':'application/json'},body:JSON.stringify({username,password:randomBytes(18).toString('base64url')})});assert(res.ok);ids.push((await db.query('select id from accounts where username=$1',[username])).rows[0].id);}
 const world=JSON.parse((await db.query('select document from worlds where id=1')).rows[0].document),battle=randomUUID();await db.query('begin');
 await db.query("update characters set hp=7,down_hp=4,weapon='spear' where id=$1",[ids[0]]);await db.query("update characters set hp=0,life='down',down_hp=4 where id=$1",[ids[1]]);await db.query("update characters set hp=0,down_hp=0,life='soul',death_q=3,death_r=4 where id=$1",[ids[2]]);
 await db.query('insert into battle_encounters(id,world_version,world_q,world_r,turn_account_id,turn_points,turn_deadline) values($1,$2,1000,1000,$3,4,$4)',[battle,world.version,ids[0],Date.now()+3600000]);
 await db.query('insert into battle_actors(encounter_id,account_id,q,r,initiative,entry_round,initiative_roll,initiative_score) values($1,$2,0,0,0,1,18,18),($1,$3,2,0,1,1,7,7)',[battle,ids[0],ids[1]]);
 await db.query("insert into battle_intents(encounter_id,attacker_id,target_id,q,r,cells,weapon,damage,min_range,max_range,move_rule,origin_q,origin_r) values($1,$2,null,2,0,$3,'spear',3,1,2,'translated_shape',0,0)",[battle,ids[0],JSON.stringify([{q:1,r:0},{q:2,r:0}])]);await db.query('commit');
 writeFileSync(file,JSON.stringify({ids,battle,state:await snapshot(ids,battle)}));console.log('Restart fixture saved: health, down, soul, equipment, initiative, attack shape');
}else{const f=JSON.parse(readFileSync(file,'utf8'));if(mode==='verify'){assert.deepEqual(await snapshot(f.ids,f.battle),f.state);console.log('PASS health, down, soul marker, equipment, initiative and multi-cell attack survive process restart');}await db.query('delete from battle_encounters where id=$1',[f.battle]);for(const id of f.ids)await db.query("delete from accounts where id=$1 and username like 'restart_life_%'",[id]);}
}finally{await db.end();}
