import assert from 'node:assert/strict';import pg from 'pg';import {readFileSync,writeFileSync} from 'node:fs';
const db=new pg.Client({host:'127.0.0.1',port:55432,user:'worldgame',database:'worldgame'});await db.connect();
async function call(path,body,cookie=''){const r=await fetch('http://127.0.0.1:8080/api'+path,{method:body===undefined?'GET':'POST',headers:{Origin:'http://127.0.0.1:5173','X-World-Request':'1','Content-Type':'application/json',Cookie:cookie},body:body===undefined?undefined:JSON.stringify(body)});assert.equal(r.status,200,path);return{data:await r.json(),cookie:r.headers.get('set-cookie')?.split(';')[0]||cookie};}
try{if(process.argv[2]==='prepare'){
 const admin=await call('/login',JSON.parse(readFileSync('../.local/dev.json','utf8'))),creds={username:'chat_restart_'+Date.now().toString(36),password:'local-restart-test-only'};await call('/register',creds);const u=await call('/login',creds);await call(`/admin/accounts/${u.data.id}/approval`,{approved:true},admin.cookie);
 const message=(await call('/chat/messages',{peer:admin.data.id,kind:'text',body:'restart persistence'},u.cookie)).data;await call('/chat/read',{peer:u.data.id,upTo:message.id},admin.cookie);
 const form=new FormData();form.append('file',new Blob([readFileSync('../.local/chat-test.gif')],{type:'image/gif'}),'test.gif');const r=await fetch('http://127.0.0.1:8080/api/chat/image',{method:'POST',headers:{Origin:'http://127.0.0.1:5173','X-World-Request':'1',Cookie:u.cookie},body:form});assert.equal(r.status,200);const image=await r.json();const ban=(await call('/admin/bans',{targetType:'account',target:u.data.id,scope:'chat',minutes:60,reason:'local restart test'},admin.cookie)).data;
 writeFileSync('../.local/chat-restart-state.json',JSON.stringify({u,admin,message,image,ban}));console.log('Prepared durable chat, image, read cursor, ban and sessions');
}else{const {u,admin,message,image}=JSON.parse(readFileSync('../.local/chat-restart-state.json'));
 try{assert((await call('/chat/messages?peer='+u.data.id,undefined,admin.cookie)).data.messages.some(m=>m.id===message.id));assert(!(await call('/chat/status',undefined,admin.cookie)).data.contacts.find(c=>c.id===u.data.id).unread);assert((await call('/chat/status',undefined,u.cookie)).data.muted);const r=await fetch('http://127.0.0.1:8080/api/chat/images/'+image.id,{headers:{Cookie:u.cookie}});assert.equal(r.status,200);assert.deepEqual(Buffer.from(await r.arrayBuffer()),readFileSync('../.local/chat-test.gif'));writeFileSync('../.local/chat-restart-report.json',JSON.stringify({passed:true,date:new Date().toISOString()}));console.log('PASS chat, original GIF, read cursor, ban and login survive backend restart');}
 finally{await db.query('delete from moderation_bans where target=$1',[u.data.id]);await db.query('delete from admin_audit where target=$1',[u.data.id]);await db.query('delete from accounts where id=$1',[u.data.id]);}
}}finally{await db.end();}
