import assert from 'node:assert/strict';import pg from 'pg';import {readFileSync,writeFileSync} from 'node:fs';import {WebSocket} from 'ws';
const base='http://127.0.0.1:8080',origin='http://127.0.0.1:5173',pause=ms=>new Promise(r=>setTimeout(r,ms)),users=[],sockets=[],bans=[],checks=[];
const db=new pg.Client({host:'127.0.0.1',port:55432,user:'worldgame',database:'worldgame'});await db.connect();
async function call(path,body,cookie='',expected=200,extra={}){const r=await fetch(base+'/api'+path,{method:body===undefined?'GET':'POST',headers:{Origin:origin,'X-World-Request':'1','Content-Type':'application/json',Cookie:cookie,...extra},body:body===undefined?undefined:JSON.stringify(body)});const data=await r.json().catch(()=>({}));assert.equal(r.status,expected,path+JSON.stringify(data));return{data,cookie:r.headers.get('set-cookie')?.split(';')[0]||cookie};}
async function socket(u,extra={}){const ws=new WebSocket('ws://127.0.0.1:8080/ws',{headers:{Origin:origin,Cookie:u.cookie,...extra}}),state={ws,events:[]};sockets.push(ws);ws.on('message',m=>state.events.push(JSON.parse(m)));await new Promise((r,j)=>{ws.once('open',r);ws.once('error',j);});return state;}
async function until(fn){for(let i=0;i<100;i++){if(fn())return;await pause(60);}throw Error('Timed out');}const pass=s=>{checks.push(s);console.log('PASS '+s);};
async function send(u,kind,body,peer=null,expected=200,extra={}){await pause(720);return call('/chat/messages',{peer,kind,body},u.cookie,expected,extra);}
async function upload(u,bytes,mime,name,expected=200){const form=new FormData();form.append('file',new Blob([bytes],{type:mime}),name);const r=await fetch(base+'/api/chat/image',{method:'POST',headers:{Origin:origin,'X-World-Request':'1',Cookie:u.cookie},body:form});const result=await r.json().catch(()=>({}));assert.equal(r.status,expected,JSON.stringify(result));return result;}
async function image(u,id,status=200){const r=await fetch(base+'/api/chat/images/'+id,{headers:{Cookie:u.cookie}});assert.equal(r.status,status);return r;}
try{
const admin=await call('/login',JSON.parse(readFileSync('../.local/dev.json','utf8'))),world=(await call('/world',undefined,admin.cookie)).data;
await call('/chat/status',undefined,'',401);
for(let i=0;i<3;i++){const credentials={username:'chat_'+Date.now().toString(36)+'_'+i,password:'local-chat-test-password'};await call('/register',credentials);const u=await call('/login',credentials);u.credentials=credentials;users.push(u);await call('/chat/messages',undefined,u.cookie,403);await call(`/admin/accounts/${u.data.id}/approval`,{approved:true},admin.cookie);}
const [a,b,c]=users,sa=await socket(a),sb=await socket(b),sc=await socket(c);
await call('/admin/bans',undefined,a.cookie,403);await call('/admin/chat/images',undefined,a.cookie,403);pass('anonymous, pending and administrator access checks');
const first=(await send(a,'text','公聊测试：<script>not code</script>')).data;assert((await call('/chat/status',undefined,b.cookie)).data.publicUnread);await call('/chat/read',{peer:null,upTo:first.id},b.cookie);assert(!(await call('/chat/status',undefined,b.cookie)).data.publicUnread);pass('public history and read dot cursor');
const before=sc.events.length,privateMessage=(await send(a,'text','仅双方的私密消息',b.data.id)).data;await until(()=>sb.events.some(e=>e.type==='chat-changed'));assert(!sc.events.slice(before).some(e=>e.type==='chat-changed'));
assert((await call('/chat/messages?peer='+a.data.id,undefined,b.cookie)).data.messages.some(m=>m.id===privateMessage.id));assert(!(await call('/chat/messages?peer='+a.data.id,undefined,c.cookie)).data.messages.some(m=>m.id===privateMessage.id));assert(!(await call('/chat/messages?peer='+a.data.id,undefined,admin.cookie)).data.messages.some(m=>m.id===privateMessage.id));assert((await call('/chat/status',undefined,b.cookie)).data.contacts.find(x=>x.id===a.data.id).unread);await call('/chat/read',{peer:a.data.id,upTo:privateMessage.id},b.cookie);assert(!(await call('/chat/status',undefined,b.cookie)).data.contacts.find(x=>x.id===a.data.id).unread);pass('private delivery, private history isolation including admin, private dots');
sb.ws.close();await send(a,'emote','heart',b.data.id);assert((await call('/chat/messages?peer='+a.data.id,undefined,b.cookie)).data.messages.some(m=>m.kind==='emote'));pass('offline private delivery and fixed emote messages');
await send(a,'emote','unknown',null,400);await send(a,'text','x'.repeat(1001),null,400);await send(a,'file','no files',null,400);pass('invalid content and unsupported files rejected');
await upload(a,Buffer.from('<script>alert(1)</script>'),'image/png','fake.png',400);await upload(a,Buffer.alloc(5*1024*1024+1),'image/png','large.png',413);pass('real image validation and 5MB size limit');
const original=await upload(a,readFileSync('../.local/chat-test.png'),'image/png','test.png');assert.equal(original.status,'active');await image(a,original.id);await image(c,original.id,404);await image(admin,original.id,404);
const im=(await send(a,'image','',b.data.id)).data;await image(b,original.id);await image(c,original.id,404);await image(admin,original.id,404);const repeated=(await send(a,'image','',b.data.id)).data;assert.equal(im.imageId,repeated.imageId);assert.equal((await db.query("select count(*) from chat_images where owner_id=$1 and status='active'",[a.data.id])).rows[0].count,'1');pass('first image direct, repeated sends reuse one image, attachment privacy');
const pending=await upload(a,readFileSync('../.local/chat-test.gif'),'image/gif','animated.gif');assert.equal(pending.status,'pending');await image(admin,pending.id);await image(b,pending.id,404);await upload(a,readFileSync('../.local/chat-test.jpg'),'image/jpeg','second.jpg',400);assert.equal((await send(a,'image','',b.data.id)).data.imageId,original.id);pass('animated GIF pending review, one request and old image remains usable');
await call('/admin/chat/images/'+pending.id,{approve:true},admin.cookie);await image(a,original.id,404);await image(b,original.id,404);assert.equal((await db.query('select data from chat_images where id=$1',[original.id])).rows[0].data,null);const history=(await call('/chat/messages?peer='+a.data.id,undefined,b.cookie)).data.messages;assert(!history.find(m=>m.id===im.id).imageAvailable);const gifResponse=await image(a,pending.id);assert.equal(gifResponse.headers.get('content-type'),'image/gif');assert.deepEqual(Buffer.from(await gifResponse.arrayBuffer()),readFileSync('../.local/chat-test.gif'));pass('approval deletes old bytes, expires historical images and preserves animated GIF');
const rejected=await upload(a,readFileSync('../.local/chat-test.jpg'),'image/jpeg','new.jpg');await call('/admin/chat/images/'+rejected.id,{approve:false},admin.cookie);assert.equal((await db.query('select data from chat_images where id=$1',[rejected.id])).rows[0].data,null);assert.equal((await send(a,'image','',b.data.id)).data.imageId,pending.id);pass('rejection deletes pending bytes and retains current image');
async function ban(type,target,scope,minutes=null){const r=(await call('/admin/bans',{targetType:type,target,scope,minutes,reason:'local test'},admin.cookie)).data;bans.push(r.id);return r.id;}
const mute=await ban('account',a.data.id,'chat',1);await send(a,'text','blocked',null,403);await send(a,'image','',null,403);await send(a,'emote','happy',null,403);await call('/emote',{code:'happy',version:world.version},a.cookie);await call('/world',undefined,a.cookie);await call('/chat/messages',undefined,a.cookie);pass('chat mute blocks text image emoji but allows map emote reading and game');
await db.query("update moderation_bans set expires_at=current_timestamp-interval '1 second' where id=$1",[mute]);await send(a,'text','到期后恢复');pass('timed restrictions expire without manual action');
const ipMute=await ban('ip','198.51.100.77','chat');await send(b,'text','blocked IP',null,403,{'X-Forwarded-For':'198.51.100.77'});await send(a,'text','same IP blocked',null,403,{'X-Forwarded-For':'198.51.100.77'});await call('/admin/bans/'+ipMute+'/revoke',{},admin.cookie);await send(b,'text','IP restriction removed',null,200,{'X-Forwarded-For':'198.51.100.77'});pass('shared IP mute and early removal');
const oldTab2=await socket(c);const newLogin=await call('/login',c.credentials);await until(()=>sc.ws.readyState===WebSocket.CLOSED&&oldTab2.ws.readyState===WebSocket.CLOSED);await call('/me',undefined,c.cookie,401);c.cookie=newLogin.cookie;await call('/me',undefined,c.cookie,200,{'X-Forwarded-For':'198.51.100.33'});const nc1=await socket(c),nc2=await socket(c);assert.equal(nc1.ws.readyState,WebSocket.OPEN);assert.equal(nc2.ws.readyState,WebSocket.OPEN);pass('new browser invalidates old sessions, shared tabs work and network change stays logged in');
const gameBan=await ban('account',c.data.id,'game');await until(()=>nc1.ws.readyState===WebSocket.CLOSED&&nc2.ws.readyState===WebSocket.CLOSED);await call('/me',undefined,c.cookie,403);await call('/login',c.credentials,'',403);await call('/admin/bans/'+gameBan+'/revoke',{},admin.cookie);await call('/me',undefined,c.cookie);pass('account game ban closes sockets, blocks login and can be lifted');
const ipSocket=await socket(b,{'X-Forwarded-For':'198.51.100.88'});const ipBan=await ban('ip','198.51.100.88','game');await until(()=>ipSocket.ws.readyState===WebSocket.CLOSED);await call('/me',undefined,b.cookie,403,{'X-Forwarded-For':'198.51.100.88'});await call('/login',b.credentials,'',403,{'X-Forwarded-For':'198.51.100.88'});await call('/me',undefined,b.cookie);await call('/admin/bans/'+ipBan+'/revoke',{},admin.cookie);pass('IP game ban uses current connection IP and does not bind session to a network');
await call('/admin/bans',{targetType:'ip',target:'127.0.0.1',scope:'game'},admin.cookie,400);await call('/admin/bans',{targetType:'account',target:admin.data.id,scope:'game'},admin.cookie,400);await call('/admin/bans',{targetType:'ip',target:'example.com',scope:'game'},admin.cookie,400);pass('self-admin lockout and hostname targets rejected');
for(let i=0;i<45;i++)await db.query("insert into chat_messages(sender_id,recipient_id,kind,body) values($1,$2,'text',$3)",[a.data.id,b.data.id,'分页 '+i]);const latest=(await call('/chat/messages?peer='+a.data.id,undefined,b.cookie)).data;assert.equal(latest.messages.length,40);assert(latest.hasMore);const older=(await call('/chat/messages?peer='+a.data.id+'&before='+latest.messages[0].id,undefined,b.cookie)).data;assert(older.messages.length>0);assert(older.messages.every(m=>m.id<latest.messages[0].id));pass('private history pagination keeps older messages scoped and ordered');
writeFileSync('../.local/chat-report.json',JSON.stringify({date:new Date().toISOString(),passed:checks.length,checks},null,2));
}finally{for(const ws of sockets)ws.close();for(const id of bans)await db.query('delete from moderation_bans where id=$1',[id]);for(const u of users){await db.query('delete from admin_audit where target=$1',[u.data.id]);await db.query('delete from accounts where id=$1',[u.data.id]);}await db.end();}
