import assert from 'node:assert/strict';import {readFileSync,writeFileSync} from 'node:fs';import pg from 'pg';import {WebSocket} from 'ws';
const db=new pg.Client({host:'127.0.0.1',port:55432,user:'worldgame',database:'worldgame'});await db.connect();const origin='http://127.0.0.1:5173',ids=[],sockets=[],checks=[],pause=ms=>new Promise(r=>setTimeout(r,ms));
async function call(path,body,cookie='',status=200){const r=await fetch('http://127.0.0.1:8080/api'+path,{method:body===undefined?'GET':'POST',headers:{Origin:origin,'X-World-Request':'1','Content-Type':'application/json',Cookie:cookie},body:body===undefined?undefined:JSON.stringify(body)});const data=await r.json();assert.equal(r.status,status,path+JSON.stringify(data));return{data,cookie:r.headers.get('set-cookie')?.split(';')[0]||cookie};}
async function connect(cookie){const ws=new WebSocket('ws://127.0.0.1:8080/ws',{headers:{Cookie:cookie,Origin:origin}}),s={ws,last:null};sockets.push(ws);ws.on('message',m=>s.last=JSON.parse(m));await new Promise((r,j)=>{ws.once('open',r);ws.once('error',j);});return s;}
async function until(fn){for(let i=0;i<100;i++){if(await fn())return;await pause(60);}throw Error('Timed out');}const pass=s=>{checks.push(s);console.log('PASS '+s);};
try{const admin=await call('/login',JSON.parse(readFileSync('../.local/dev.json','utf8'))),w=(await call('/world',undefined,admin.cookie)).data,users=[];
await call('/emote',{code:'happy',version:w.version},'',401);
for(let i=0;i<2;i++){const credentials={username:'emote_'+Date.now().toString(36)+'_'+i,password:'local-emote-test-password'};await call('/register',credentials);const u=await call('/login',credentials);ids.push(u.data.id);await call('/emote',{code:'happy',version:w.version},u.cookie,403);await call(`/admin/accounts/${u.data.id}/approval`,{approved:true},admin.cookie);users.push(u);}
const [a,b]=users,sa=await connect(a.cookie),sb=await connect(b.cookie),send=(u,code,status=200)=>call('/emote',{code,version:w.version},u.cookie,status);
await send(a,'not-a-real-emote',400);await call('/emote',{code:'happy',version:'old'},a.cookie,400);await call('/emote',{version:w.version},a.cookie,400);pass('anonymous, pending, invalid code and stale world are rejected');
const first=(await send(a,'happy')).data;assert.equal(first.expiresAt-first.startedAt,3000);await until(()=>sb.last?.emotes.some(e=>e.accountId===a.data.id&&e.code==='happy'));await send(a,'sad',429);pass('shared three-second emote and burst limit');
await send(b,'heart');await pause(300);await send(a,'question');await until(()=>sb.last.emotes.find(e=>e.accountId===a.data.id)?.code==='question');assert.equal(sb.last.emotes.filter(e=>e.accountId===a.data.id).length,1);assert(sb.last.emotes.some(e=>e.accountId===b.data.id));pass('replacement keeps one bubble per player without affecting others');
await until(()=>!sa.last.emotes.length&&!sb.last.emotes.length);pass('expired emotes disappear on both clients');
const tree=sa.last.resources.find(n=>n.kind==='wood'&&n.readyAt===0),neighbor=w.tiles.find(t=>(Math.abs(t.q-tree.q)+Math.abs(t.r-tree.r)+Math.abs(t.q+t.r-tree.q-tree.r))/2===1&&!['ocean','river','mountain'].includes(t.terrain));
await db.query('update accounts set q=$1,r=$2 where id=$3',[tree.q,tree.r,a.data.id]);await call('/collect',{q:tree.q,r:tree.r,version:w.version},a.cookie);await until(()=>sa.last.actions.some(x=>x.accountId===a.data.id));const action=sa.last.actions.find(x=>x.accountId===a.data.id);await send(a,'thumb');await until(()=>sa.last.emotes.some(e=>e.code==='thumb'));assert.deepEqual(sa.last.actions.find(x=>x.accountId===a.data.id),action);await until(async()=>(await call('/inventory',undefined,a.cookie)).data.find(i=>i.code==='wood').quantity===1);pass('emote does not cancel or restart chopping and reward is preserved');
await call('/move',{q:neighbor.q,r:neighbor.r,version:w.version},a.cookie);await send(a,'ok');await until(()=>sa.last.players.some(p=>p.id===a.data.id&&p.q===neighbor.q&&p.r===neighbor.r&&!p.moving));pass('emote does not cancel movement');
await pause(300);for(const code of ['sad','angry','help']){await send(a,code);await pause(300);}pass('all eight fixed codes accepted');
await call(`/admin/accounts/${a.data.id}/approval`,{approved:false},admin.cookie);await until(()=>!sb.last.emotes.some(e=>e.accountId===a.data.id));await send(a,'happy',403);pass('revocation clears bubble and denies further sends');
writeFileSync('../.local/emote-report.json',JSON.stringify({passed:checks.length,checks,date:new Date().toISOString()},null,2));
}finally{for(const ws of sockets)ws.close();for(const id of ids){await db.query('delete from admin_audit where target=$1',[id]);await db.query('delete from accounts where id=$1',[id]);}await db.end();}
