import assert from 'node:assert/strict';
import {readFileSync,writeFileSync} from 'node:fs';
import {randomUUID,randomBytes} from 'node:crypto';
import {WebSocket} from 'ws';
import pg from 'pg';
const db=new pg.Client({host:'127.0.0.1',port:55432,user:'worldgame',database:'worldgame'}),users=[],sockets=[],containers=[],battles=[],monsters=[],checks=[];
const pass=s=>{checks.push(s);console.log('PASS '+s)};
async function call(path,body,u,status=200){const r=await fetch('http://127.0.0.1:8080/api'+path,{method:body===undefined?'GET':'POST',headers:{Origin:'http://127.0.0.1:5173',Cookie:u?.cookie||'','X-World-Request':'1','Content-Type':'application/json'},body:body===undefined?undefined:JSON.stringify(body)});const data=await r.json();assert.equal(r.status,status,path+': '+JSON.stringify(data));return {data,cookie:r.headers.get('set-cookie')?.split(';')[0]||u?.cookie};}
await db.connect();let keep=false;
try{
 const admin=await call('/login',JSON.parse(readFileSync(new URL('../.local/dev.json',import.meta.url)))),world=(await call('/world',undefined,admin)).data;
 for(let i=0;i<2;i++){const credentials={username:'loot_'+Date.now().toString(36)+'_'+i,password:randomBytes(16).toString('base64url')};await call('/register',credentials);const u=await call('/login',credentials);u.credentials=credentials;users.push(u);await call(`/admin/accounts/${u.data.id}/approval`,{approved:true},admin);const ws=new WebSocket('ws://127.0.0.1:8080/ws',{headers:{Origin:'http://127.0.0.1:5173',Cookie:u.cookie}});sockets.push(ws);await new Promise((r,j)=>{ws.once('message',r);ws.once('error',j)});}
 const [a,b]=users;const occupied=(await db.query('select q,r from accounts where entered=true')).rows,cell=world.tiles.find(t=>t.terrain==='plain'&&!occupied.some(p=>p.q===t.q&&p.r===t.r));
 for(const u of users)await db.query('update accounts set q=$1,r=$2 where id=$3',[cell.q,cell.r,u.data.id]);
 const cmd=(u,action,body={},status=200)=>call('/loot/action',{version:world.version,battleId:null,action,...body},u,status);
 const list=async(u,battle=null)=>(await call('/loot?version='+world.version+(battle?'&battleId='+battle:''),undefined,u)).data;
 const inv=async u=>(await call('/inventory',undefined,u)).data;
 await call(`/admin/accounts/${a.data.id}/items`,{code:'wood',quantity:5},admin);
 await cmd(a,'dropItem',{code:'wood',quantity:3});let bag=(await list(a)).ground.find(x=>x.kind==='bag');containers.push(bag.id);assert.equal(bag.itemCount,3);assert(Math.abs(bag.expiresAt-Date.now()-1800000)<4000);assert.equal((await inv(a)).find(x=>x.code==='wood').quantity,2);pass('Dropping items conserves inventory and creates 30-minute bag');
 const results=await Promise.all(users.map(u=>fetch('http://127.0.0.1:8080/api/loot/action',{method:'POST',headers:{Origin:'http://127.0.0.1:5173',Cookie:u.cookie,'X-World-Request':'1','Content-Type':'application/json'},body:JSON.stringify({version:world.version,action:'takeAll',containerId:bag.id})})));assert.deepEqual(results.map(r=>r.status).sort(),[200,400]);assert.equal((await inv(a)).find(x=>x.code==='wood').quantity+(await inv(b)).find(x=>x.code==='wood').quantity,5);pass('Concurrent public claims deliver exactly once');
 async function corpse(){const id=randomUUID();containers.push(id);await db.query("insert into loot_containers(id,kind,name,source_kind,world_version,q,r,created_at,expires_at) values($1,'corpse','测试山魈的尸体','monster',$2,$3,$4,$5,$6)",[id,world.version,cell.q,cell.r,Date.now(),Date.now()+60000]);await db.query("insert into loot_items values($1,'stone',2)",[id]);return id;}
 let c=await corpse(),c2=await corpse();await cmd(a,'carry',{containerId:c});await cmd(a,'carry',{containerId:c2});let carried=(await list(a)).carried;assert.equal(carried.length,2);assert(carried.every(x=>x.expiresAt===null&&x.itemCount===2));await call('/loot/'+c+'?version='+world.version,undefined,b,400);pass('Corpses occupy independent instances; contained items follow carrier; others cannot read');
 await cmd(a,'nest',{containerId:c},400);await cmd(a,'dropCorpse',{containerId:c});let dropped=(await list(a)).ground.find(x=>x.id===c);assert(dropped.expiresAt>Date.now()+1795000);pass('No corpse nesting; re-drop resets full lifetime');
 await db.query('update loot_containers set expires_at=$1 where id=$2',[Date.now()-1,c]);await cmd(a,'takeAll',{containerId:c},400);await new Promise(r=>setTimeout(r,700));assert.equal((await db.query('select count(*)::int n from loot_items where container_id=$1',[c])).rows[0].n,0);assert((await list(a)).carried.some(x=>x.id===c2));pass('Expired ground containers and contents disappear; carried corpses survive');
 c=await corpse();let battle=(await call('/battle/start',{targetId:b.data.id,version:world.version},a)).data.id;battles.push(battle);
 async function turn(){await db.query('update battle_encounters set turn_account_id=$1,turn_points=6,turn_deadline=$2 where id=$3',[a.data.id,Date.now()+120000,battle]);await db.query('update battle_actors set q=0,r=0,entry_round=1 where encounter_id=$1 and account_id=$2',[battle,a.data.id]);await db.query('update battle_actors set q=3,r=0,entry_round=1 where encounter_id=$1 and account_id=$2',[battle,b.data.id]);}
 await turn();await db.query('update loot_containers set battle_q=1,battle_r=0 where id=$1',[c]);const bcmd=(action,body={},status=200)=>cmd(a,action,{battleId:battle,...body},status);const points=async()=>(await call('/battle/current',undefined,a)).data.turnPoints;
 await call('/loot/'+c+'?version='+world.version+'&battleId='+battle,undefined,a,400);await bcmd('takeAll',{containerId:c},400);assert.equal(await points(),6);pass('Adjacent corpse denied without cost');
 await db.query('update loot_containers set battle_q=0,battle_r=0 where id=$1',[c]);await call('/loot/'+c+'?version='+world.version+'&battleId='+battle,undefined,a);assert.equal(await points(),6);await bcmd('take',{containerId:c,code:'stone',quantity:9},400);assert.equal(await points(),6);await bcmd('takeAll',{containerId:c});assert.equal(await points(),4);await bcmd('takeAll',{containerId:c},400);assert.equal(await points(),4);await bcmd('carry',{containerId:c});assert.equal(await points(),2);pass('Same-cell viewing free; take-all/carry each cost 2; failed actions free');
 await db.query('update battle_encounters set turn_points=1 where id=$1',[battle]);await bcmd('take',{containerId:c2,code:'stone',quantity:1},400);assert.equal(await points(),1);await cmd(a,'dropItem',{code:'wood',quantity:1},400);pass('AP and stale world/battle context enforced');
 // A disposable monster exercises actual death, corpse generation and 1v1 close.
 const npc=randomUUID();monsters.push(npc);await db.query("insert into characters(id,kind,name,q,r,hp,max_hp,down_hp,max_down_hp,life,bind_q,bind_r,next_move) values($1,'monster','尸体测试兽',$2,$3,0,12,1,6,'down',$2,$3,$4)",[npc,cell.q,cell.r,Date.now()+999999]);
 await db.query('delete from battle_actors where encounter_id=$1 and account_id=$2',[battle,b.data.id]);await db.query('insert into battle_actors(encounter_id,account_id,q,r,initiative,entry_round) values($1,$2,1,0,9,1)',[battle,npc]);await turn();
 await call('/battle/attack',{battleId:battle,q:1,r:0},a);await call('/battle/step',{battleId:battle,q:0,r:-1},a);
 assert.equal((await call('/battle/current',undefined,a)).data.active,false);let corpseRows=(await db.query('select * from loot_containers where source_id=$1',[npc])).rows;assert.equal(corpseRows.length,1);containers.push(corpseRows[0].id);assert.equal(corpseRows[0].battle_id,null);assert.equal(corpseRows[0].q,cell.q);assert.equal((await list(a)).ground.filter(x=>x.sourceId===npc).length,1);pass('Actual monster death leaves one corpse; 1v1 ends and corpse is on original world cell');
 await call('/character/action',{action:'surrender'},b);assert.equal((await db.query('select count(*)::int n from loot_containers where source_id=$1',[b.data.id])).rows[0].n,0);pass('Player death remains soul flow with no corpse');
 if(process.argv.includes('--keep')){keep=true;writeFileSync(new URL('../.local/loot-fixture.json',import.meta.url),JSON.stringify({users,containers,battles,monsters,cell,version:world.version}));}
 writeFileSync(new URL('../.local/loot-report.json',import.meta.url),JSON.stringify({date:new Date().toISOString(),checks},null,2));
}finally{for(const ws of sockets)ws.close();if(!keep){for(const id of containers)await db.query('delete from loot_containers where id=$1',[id]);for(const id of battles)await db.query('delete from battle_encounters where id=$1',[id]);for(const id of monsters)await db.query('delete from characters where id=$1',[id]);for(const u of users){await db.query('delete from admin_audit where target like $1',[u.data.id+'%']);await db.query('delete from accounts where id=$1',[u.data.id]);}}await db.end();}
