import assert from 'node:assert/strict';import {readFileSync,writeFileSync} from 'node:fs';import {randomBytes} from 'node:crypto';import {WebSocket} from 'ws';
const base='https://qingtaixieai.com',pause=ms=>new Promise(r=>setTimeout(r,ms)),users=[],sockets=[];
const password=readFileSync('../.local/admin-access.txt','utf8').split(/\r?\n/).find(l=>l.startsWith('管理员密码：')).slice('管理员密码：'.length);
async function call(path,body,cookie='',status=200){const r=await fetch(base+'/api'+path,{method:body===undefined?'GET':'POST',headers:{Origin:base,'X-World-Request':'1','Content-Type':'application/json',Cookie:cookie},body:body===undefined?undefined:JSON.stringify(body),signal:AbortSignal.timeout(15000)});const data=await r.json();assert.equal(r.status,status,path+JSON.stringify(data));return{data,cookie:r.headers.get('set-cookie')?.split(';')[0]||cookie};}
async function until(fn){for(let i=0;i<80;i++){if(fn())return;await pause(80);}throw Error('Timed out');}
async function connect(cookie){const ws=new WebSocket('wss://qingtaixieai.com/ws',{headers:{Cookie:cookie,Origin:base}}),s={ws,last:null};sockets.push(ws);ws.on('message',m=>s.last=JSON.parse(m));await new Promise((r,j)=>{ws.once('open',r);ws.once('error',j);});return s;}
try{const admin=await call('/login',{username:'admin',password}),world=(await call('/world',undefined,admin.cookie)).data;await call('/emote',{code:'happy',version:world.version},'',401);
for(let i=0;i<2;i++){const credentials={username:'deploy_qa_'+Date.now().toString(36)+'_'+i,password:randomBytes(16).toString('base64url')};await call('/register',credentials);const u=await call('/login',credentials);users.push(u);writeFileSync('../.local/production-emote-ids.json',JSON.stringify(users.map(u=>({id:u.data.id,username:u.data.username}))));await call('/emote',{code:'happy',version:world.version},u.cookie,403);await call(`/admin/accounts/${u.data.id}/approval`,{approved:true},admin.cookie);}
const [a,b]=users,sa=await connect(a.cookie),sb=await connect(b.cookie);await call('/emote',{code:'happy',version:world.version},a.cookie);await until(()=>sb.last?.emotes.some(e=>e.accountId===a.data.id&&e.code==='happy'));const e=sb.last.emotes.find(e=>e.accountId===a.data.id);assert.equal(e.expiresAt-e.startedAt,3000);await pause(300);await call('/emote',{code:'heart',version:world.version},a.cookie);await until(()=>sb.last?.emotes.find(e=>e.accountId===a.data.id)?.code==='heart');assert.equal(sb.last.emotes.filter(e=>e.accountId===a.data.id).length,1);await until(()=>!sa.last?.emotes.some(e=>e.accountId===a.data.id)&&!sb.last?.emotes.some(e=>e.accountId===a.data.id));writeFileSync('../.local/production-emote-report.json',JSON.stringify({passed:true,date:new Date().toISOString(),checks:['anonymous and pending denied','shared emote over public WSS','replace old bubble','three-second expiry on both clients']},null,2));console.log('PASS public emote permissions, dual-client delivery, replacement and expiry');
}finally{for(const ws of sockets)ws.close();}
