import assert from 'node:assert/strict';import {readFileSync,writeFileSync} from 'node:fs';import {randomBytes} from 'node:crypto';import {WebSocket} from 'ws';
const base='https://qingtaixieai.com',pause=ms=>new Promise(r=>setTimeout(r,ms)),users=[],sockets=[],checks=[];
const password=readFileSync('../.local/admin-access.txt','utf8').split(/\r?\n/).find(l=>l.startsWith('管理员密码：')).slice('管理员密码：'.length);
async function call(path,body,cookie='',expected=200){const r=await fetch(base+'/api'+path,{method:body===undefined?'GET':'POST',headers:{Origin:base,'X-World-Request':'1','Content-Type':'application/json',Cookie:cookie},body:body===undefined?undefined:JSON.stringify(body),signal:AbortSignal.timeout(20000)});const data=await r.json();assert.equal(r.status,expected,path+JSON.stringify(data));return{data,cookie:r.headers.get('set-cookie')?.split(';')[0]||cookie};}
async function socket(cookie){const ws=new WebSocket('wss://qingtaixieai.com/ws',{headers:{Origin:base,Cookie:cookie}}),s={ws,events:[]};sockets.push(ws);ws.on('message',m=>s.events.push(JSON.parse(m)));await new Promise((r,j)=>{ws.once('open',r);ws.once('error',j);});return s;}
async function until(fn){for(let i=0;i<100;i++){if(fn())return;await pause(100);}throw Error('Timed out');}
async function upload(u,file,mime){const form=new FormData();form.append('file',new Blob([readFileSync(file)],{type:mime}),'check.'+mime.split('/')[1]);const r=await fetch(base+'/api/chat/image',{method:'POST',headers:{Origin:base,'X-World-Request':'1',Cookie:u.cookie},body:form});assert.equal(r.status,200);return r.json();}
const pass=s=>{checks.push(s);console.log('PASS '+s);};
try{const admin=await call('/login',{username:'admin',password});await call('/chat/status',undefined,'',401);
 for(let i=0;i<2;i++){const credentials={username:'deploy_qa_'+Date.now().toString(36)+'_'+i,password:randomBytes(16).toString('base64url')};await call('/register',credentials);const u=await call('/login',credentials);u.credentials=credentials;users.push(u);writeFileSync('../.local/production-chat-ids.json',JSON.stringify(users.map(x=>({id:x.data.id,username:x.data.username}))));await call('/chat/messages',undefined,u.cookie,403);await call(`/admin/accounts/${u.data.id}/approval`,{approved:true},admin.cookie);}
 const[a,b]=users,sa=await socket(a.cookie),sb=await socket(b.cookie);const m=(await call('/chat/messages',{peer:b.data.id,kind:'text',body:'部署验收：私聊同步'},a.cookie)).data;await until(()=>sb.events.some(e=>e.type==='chat-changed'));assert((await call('/chat/status',undefined,b.cookie)).data.contacts.find(c=>c.id===a.data.id).unread);assert((await call('/chat/messages?peer='+a.data.id,undefined,b.cookie)).data.messages.some(x=>x.id===m.id));assert(!(await call('/chat/messages?peer='+a.data.id,undefined,admin.cookie)).data.messages.some(x=>x.id===m.id));await call('/chat/read',{peer:a.data.id,upTo:m.id},b.cookie);assert(!(await call('/chat/status',undefined,b.cookie)).data.contacts.find(c=>c.id===a.data.id).unread);pass('HTTPS permissions, WSS private delivery, read dots and administrator privacy');
 const old=await upload(a,'../.local/chat-test.png','image/png');await pause(800);await call('/chat/messages',{peer:b.data.id,kind:'image'},a.cookie);assert.equal((await fetch(base+'/api/chat/images/'+old.id,{headers:{Cookie:b.cookie}})).status,200);assert.equal((await fetch(base+'/api/chat/images/'+old.id,{headers:{Cookie:admin.cookie}})).status,404);
 const next=await upload(a,'../.local/chat-test.gif','image/gif');assert.equal(next.status,'pending');await call('/admin/chat/images/'+next.id,{approve:true},admin.cookie);assert.equal((await fetch(base+'/api/chat/images/'+old.id,{headers:{Cookie:b.cookie}})).status,404);await pause(800);await call('/chat/messages',{peer:b.data.id,kind:'image'},a.cookie);const gif=await fetch(base+'/api/chat/images/'+next.id,{headers:{Cookie:b.cookie}});assert.deepEqual(Buffer.from(await gif.arrayBuffer()),readFileSync('../.local/chat-test.gif'));pass('Multipart image upload, private image access, approval and original GIF bytes');
 const ban=(await call('/admin/bans',{targetType:'account',target:a.data.id,scope:'chat',minutes:30,reason:'temporary deployment test'},admin.cookie)).data;assert((await call('/chat/status',undefined,a.cookie)).data.muted);await call('/chat/messages',{peer:b.data.id,kind:'text',body:'must be denied'},a.cookie,403);const banId=typeof ban==='string'?ban:ban.id;await call('/admin/bans/'+banId+'/revoke',{},admin.cookie);assert(!(await call('/chat/status',undefined,a.cookie)).data.muted);pass('Account mute and manual unmute');
 const replacement=await call('/login',a.credentials);await until(()=>sa.ws.readyState===WebSocket.CLOSED);await call('/chat/status',undefined,a.cookie,401);await call('/chat/status',undefined,replacement.cookie);pass('New browser login invalidates and disconnects previous session');
 writeFileSync('../.local/production-chat-report.json',JSON.stringify({passed:true,date:new Date().toISOString(),checks},null,2));
}finally{for(const ws of sockets)ws.close();}
